package com.idphoto.app.ui

import androidx.compose.runtime.*

/**
 * Hệ thống đa ngôn ngữ — VI, EN, JA, ZH.
 * Tương ứng mockup HTML i18n.
 */

enum class AppLanguage(val code: String, val label: String, val nativeName: String) {
    VI("vi", "VI", "Tiếng Việt"),
    EN("en", "EN", "English"),
    JA("ja", "JA", "日本語"),
    ZH("zh", "ZH", "中文"),
}

data class Strings(
    // Splash
    val splashSub: String,

    // Home
    val homeSub: String,
    val btnCamera: String,
    val btnCameraSub: String,
    val btnGallery: String,
    val btnGallerySub: String,
    val popularSizes: String,
    val popularSizesSub: String,
    val viewAllSizes: String,

    // Size labels
    val szPassport: String,
    val szResume: String,

    // Size select
    val selectSize: String,
    val searchPlaceholder: String,
    val customSize: String,
    val customSizeSub: String,

    // Camera
    val guideTxt: String,
    val tipLight: String,
    val tipFace: String,
    val tipBg: String,

    // Edit
    val editTitle: String,
    val save: String,
    val tCrop: String,
    val tBg: String,
    val tColor: String,
    val tBright: String,
    val tSuit: String,
    val tRotate: String,
    val tPrint: String,

    // Print
    val printTitle: String,
    val pQty: String,
    val pPaper: String,
    val pCut: String,
    val pDownload: String,
    val pPrint: String,

    // Settings
    val settingsTitle: String,
    val sLangSection: String,
    val sLanguage: String,
    val sPhotoSection: String,
    val sQuality: String,
    val sFormat: String,
    val sWatermark: String,
    val sWatermarkOff: String,
    val sAiSection: String,
    val sFaceAi: String,
    val sFaceAiSub: String,
    val sAutoBg: String,
    val sAutoBgSub: String,
    val sBeauty: String,
    val sBeautyMode: String,
    val sPrintSection: String,
    val sPaperDefault: String,
    val sCutDefault: String,
    val sCutOn: String,
    val sOther: String,
    val sPrivacy: String,
    val sPrivacySub: String,
    val sHelp: String,
    val sRate: String,
    val sVersion: String,
    val chooseLang: String,

    // Appearance / Dark mode
    val sAppearance: String,
    val sDarkMode: String,
    val sDarkModeAuto: String,
    val sDarkModeLight: String,
    val sDarkModeDark: String,

    // Processing pipeline
    val processing: String,
    val pipelineFaceMesh: String,
    val pipelineAlignment: String,
    val pipelineQuality: String,
    val pipelineSegmentation: String,
    val pipelineExport: String,

    // Face detection
    val noFaceDetected: String,
    val noFaceMessage: String,

    // Save
    val saveSuccess: String,
    val saveSuccessMessage: String,

    // Save options dialog
    val saveOptionsTitle: String,
    val savePhotoSize: String,
    val savePrintCopies: String,
    val saveFormat: String,
    val saveSingleOnly: String,
    val saveWithPrintLayout: String,
    val saveSinglePhoto: String,
    val savePrintLayoutLabel: String,
    val savePhotosPerSheet: String,

    // Common
    val back: String,
    val next: String,
    val cancel: String,
    val done: String,
    val error: String,
    val retry: String,
)

val ViStrings = Strings(
    splashSub = "Ảnh thẻ chuyên nghiệp",
    homeSub = "Chụp ảnh thẻ chuyên nghiệp",
    btnCamera = "Chụp ảnh",
    btnCameraSub = "Chụp mới",
    btnGallery = "Thư viện",
    btnGallerySub = "Chọn ảnh có sẵn",
    popularSizes = "Kích cỡ phổ biến",
    popularSizesSub = "Chọn nhanh và chụp ảnh",
    viewAllSizes = "XEM TẤT CẢ KÍCH CỠ",
    szPassport = "Hộ chiếu, Visa",
    szResume = "Sơ yếu lý lịch",
    selectSize = "Chọn kích thước",
    searchPlaceholder = "Tìm kiếm kích thước, quốc gia...",
    customSize = "Tùy chỉnh kích thước",
    customSizeSub = "Nhập kích thước tùy ý",
    guideTxt = "Đặt khuôn mặt vào khung hình",
    tipLight = "Ánh sáng tốt",
    tipFace = "Giữ thẳng mặt",
    tipBg = "Phông nền OK",
    editTitle = "Chỉnh sửa",
    save = "Lưu",
    tCrop = "Cắt",
    tBg = "Xóa phông",
    tColor = "Đổi nền",
    tBright = "Độ sáng",
    tSuit = "Đổi áo",
    tRotate = "Xoay",
    tPrint = "In ảnh",
    printTitle = "Bố cục in",
    pQty = "Số lượng",
    pPaper = "Khổ giấy",
    pCut = "Đường cắt",
    pDownload = "Tải ảnh",
    pPrint = "In ngay",
    settingsTitle = "Cài đặt",
    sLangSection = "Ngôn ngữ",
    sLanguage = "Ngôn ngữ",
    sPhotoSection = "Ảnh & Chất lượng",
    sQuality = "Chất lượng ảnh",
    sFormat = "Định dạng lưu",
    sWatermark = "Watermark",
    sWatermarkOff = "Tắt",
    sAiSection = "AI & Tự động",
    sFaceAi = "Nhận diện khuôn mặt",
    sFaceAiSub = "Tự động căn chỉnh vị trí",
    sAutoBg = "Tự động xóa phông",
    sAutoBgSub = "Xóa nền khi chụp",
    sBeauty = "Tự động làm đẹp",
    sBeautyMode = "Tự nhiên",
    sPrintSection = "In ảnh",
    sPaperDefault = "Khổ giấy mặc định",
    sCutDefault = "Đường cắt mặc định",
    sCutOn = "Bật",
    sOther = "Khác",
    sPrivacy = "Quyền riêng tư",
    sPrivacySub = "Xử lý ngoại tuyến",
    sHelp = "Trợ giúp",
    sRate = "Đánh giá ứng dụng",
    sVersion = "Phiên bản",
    chooseLang = "Chọn ngôn ngữ",
    sAppearance = "Giao diện",
    sDarkMode = "Chế độ tối",
    sDarkModeAuto = "Hệ thống",
    sDarkModeLight = "Sáng",
    sDarkModeDark = "Tối",
    processing = "Đang xử lý ảnh...",
    pipelineFaceMesh = "Nhận diện khuôn mặt",
    pipelineAlignment = "Căn chỉnh khuôn mặt",
    pipelineQuality = "Kiểm tra chất lượng",
    pipelineSegmentation = "Tách nền ảnh",
    pipelineExport = "Xuất ảnh thẻ",
    noFaceDetected = "Không phát hiện khuôn mặt",
    noFaceMessage = "Không tìm thấy khuôn mặt người trong ảnh. Vui lòng chụp lại hoặc chọn ảnh khác.",
    saveSuccess = "Đã lưu ảnh!",
    saveSuccessMessage = "Ảnh đã được lưu vào thư viện ảnh của bạn.",
    saveOptionsTitle = "Tùy chọn lưu ảnh",
    savePhotoSize = "Cỡ ảnh",
    savePrintCopies = "Số ảnh in",
    saveFormat = "Định dạng",
    saveSingleOnly = "Chỉ lưu ảnh đơn",
    saveWithPrintLayout = "Lưu kèm bố cục in",
    saveSinglePhoto = "Ảnh đơn",
    savePrintLayoutLabel = "Bố cục in",
    savePhotosPerSheet = "%d ảnh/tờ",
    back = "Quay lại",
    next = "Tiếp tục",
    cancel = "Hủy",
    done = "Xong",
    error = "Lỗi",
    retry = "Thử lại",
)

val EnStrings = Strings(
    splashSub = "Professional ID Photos",
    homeSub = "Professional ID Photo Maker",
    btnCamera = "Camera",
    btnCameraSub = "Take new photo",
    btnGallery = "Gallery",
    btnGallerySub = "Choose existing",
    popularSizes = "Popular Sizes",
    popularSizesSub = "Quick select and shoot",
    viewAllSizes = "VIEW ALL SIZES",
    szPassport = "Passport, Visa",
    szResume = "Resume / CV",
    selectSize = "Select Size",
    searchPlaceholder = "Search size, country...",
    customSize = "Custom Size",
    customSizeSub = "Enter custom dimensions",
    guideTxt = "Position your face in the frame",
    tipLight = "Good lighting",
    tipFace = "Keep face straight",
    tipBg = "Background OK",
    editTitle = "Edit Photo",
    save = "Save",
    tCrop = "Crop",
    tBg = "Remove BG",
    tColor = "Background",
    tBright = "Brightness",
    tSuit = "Outfit",
    tRotate = "Rotate",
    tPrint = "Print",
    printTitle = "Print Layout",
    pQty = "Quantity",
    pPaper = "Paper Size",
    pCut = "Cut Lines",
    pDownload = "Download",
    pPrint = "Print Now",
    settingsTitle = "Settings",
    sLangSection = "Language",
    sLanguage = "Language",
    sPhotoSection = "Photo & Quality",
    sQuality = "Photo Quality",
    sFormat = "Save Format",
    sWatermark = "Watermark",
    sWatermarkOff = "Off",
    sAiSection = "AI & Auto",
    sFaceAi = "Face Detection",
    sFaceAiSub = "Auto-align position",
    sAutoBg = "Auto Remove BG",
    sAutoBgSub = "Remove background on capture",
    sBeauty = "Auto Beauty",
    sBeautyMode = "Natural",
    sPrintSection = "Printing",
    sPaperDefault = "Default Paper Size",
    sCutDefault = "Default Cut Lines",
    sCutOn = "On",
    sOther = "Other",
    sPrivacy = "Privacy",
    sPrivacySub = "Offline processing",
    sHelp = "Help & Support",
    sRate = "Rate this app",
    sVersion = "Version",
    chooseLang = "Choose Language",
    sAppearance = "Appearance",
    sDarkMode = "Dark Mode",
    sDarkModeAuto = "System",
    sDarkModeLight = "Light",
    sDarkModeDark = "Dark",
    processing = "Processing photo...",
    pipelineFaceMesh = "Face Detection",
    pipelineAlignment = "Face Alignment",
    pipelineQuality = "Quality Check",
    pipelineSegmentation = "Background Removal",
    pipelineExport = "Export ID Photo",
    noFaceDetected = "No face detected",
    noFaceMessage = "No human face was found in the photo. Please retake or choose another image.",
    saveSuccess = "Photo saved!",
    saveSuccessMessage = "Photo has been saved to your gallery.",
    saveOptionsTitle = "Save Options",
    savePhotoSize = "Photo Size",
    savePrintCopies = "Print Copies",
    saveFormat = "Format",
    saveSingleOnly = "Save single photo only",
    saveWithPrintLayout = "Save with print layout",
    saveSinglePhoto = "Single Photo",
    savePrintLayoutLabel = "Print Layout",
    savePhotosPerSheet = "%d photos/sheet",
    back = "Back",
    next = "Next",
    cancel = "Cancel",
    done = "Done",
    error = "Error",
    retry = "Retry",
)

val JaStrings = Strings(
    splashSub = "プロの証明写真",
    homeSub = "プロの証明写真アプリ",
    btnCamera = "撮影",
    btnCameraSub = "新しく撮る",
    btnGallery = "ギャラリー",
    btnGallerySub = "既存の写真を選択",
    popularSizes = "よく使うサイズ",
    popularSizesSub = "すぐに選んで撮影",
    viewAllSizes = "すべてのサイズを見る",
    szPassport = "パスポート・ビザ",
    szResume = "履歴書",
    selectSize = "サイズを選択",
    searchPlaceholder = "サイズ、国名を検索...",
    customSize = "カスタムサイズ",
    customSizeSub = "任意のサイズを入力",
    guideTxt = "顔を枠内に合わせてください",
    tipLight = "照明OK",
    tipFace = "正面を向く",
    tipBg = "背景OK",
    editTitle = "写真を編集",
    save = "保存",
    tCrop = "切取",
    tBg = "背景除去",
    tColor = "背景色",
    tBright = "明るさ",
    tSuit = "衣装",
    tRotate = "回転",
    tPrint = "印刷",
    printTitle = "印刷レイアウト",
    pQty = "枚数",
    pPaper = "用紙サイズ",
    pCut = "切取線",
    pDownload = "ダウンロード",
    pPrint = "印刷する",
    settingsTitle = "設定",
    sLangSection = "言語",
    sLanguage = "言語",
    sPhotoSection = "写真と品質",
    sQuality = "写真品質",
    sFormat = "保存形式",
    sWatermark = "ウォーターマーク",
    sWatermarkOff = "オフ",
    sAiSection = "AI & 自動",
    sFaceAi = "顔認識",
    sFaceAiSub = "自動位置調整",
    sAutoBg = "自動背景除去",
    sAutoBgSub = "撮影時に背景を除去",
    sBeauty = "自動美肌",
    sBeautyMode = "ナチュラル",
    sPrintSection = "印刷",
    sPaperDefault = "デフォルト用紙サイズ",
    sCutDefault = "デフォルト切取線",
    sCutOn = "オン",
    sOther = "その他",
    sPrivacy = "プライバシー",
    sPrivacySub = "オフライン処理",
    sHelp = "ヘルプ",
    sRate = "アプリを評価",
    sVersion = "バージョン",
    chooseLang = "言語を選択",
    sAppearance = "外観",
    sDarkMode = "ダークモード",
    sDarkModeAuto = "システム",
    sDarkModeLight = "ライト",
    sDarkModeDark = "ダーク",
    processing = "処理中...",
    pipelineFaceMesh = "顔認識",
    pipelineAlignment = "顔の位置調整",
    pipelineQuality = "品質チェック",
    pipelineSegmentation = "背景除去",
    pipelineExport = "証明写真を出力",
    noFaceDetected = "顔が検出されません",
    noFaceMessage = "写真に人の顔が見つかりませんでした。撮り直すか、別の写真を選択してください。",
    saveSuccess = "写真を保存しました！",
    saveSuccessMessage = "写真がギャラリーに保存されました。",
    saveOptionsTitle = "保存オプション",
    savePhotoSize = "写真サイズ",
    savePrintCopies = "印刷枚数",
    saveFormat = "フォーマット",
    saveSingleOnly = "単体写真のみ保存",
    saveWithPrintLayout = "印刷レイアウト付きで保存",
    saveSinglePhoto = "単体写真",
    savePrintLayoutLabel = "印刷レイアウト",
    savePhotosPerSheet = "%d枚/シート",
    back = "戻る",
    next = "次へ",
    cancel = "キャンセル",
    done = "完了",
    error = "エラー",
    retry = "再試行",
)

val ZhStrings = Strings(
    splashSub = "专业证件照",
    homeSub = "专业证件照制作",
    btnCamera = "拍照",
    btnCameraSub = "拍摄新照片",
    btnGallery = "相册",
    btnGallerySub = "选择已有照片",
    popularSizes = "常用尺寸",
    popularSizesSub = "快速选择并拍摄",
    viewAllSizes = "查看所有尺寸",
    szPassport = "护照、签证",
    szResume = "简历",
    selectSize = "选择尺寸",
    searchPlaceholder = "搜索尺寸、国家...",
    customSize = "自定义尺寸",
    customSizeSub = "输入自定义尺寸",
    guideTxt = "将面部对准框内",
    tipLight = "光线良好",
    tipFace = "保持正面",
    tipBg = "背景OK",
    editTitle = "编辑照片",
    save = "保存",
    tCrop = "裁剪",
    tBg = "去背景",
    tColor = "换背景",
    tBright = "亮度",
    tSuit = "换装",
    tRotate = "旋转",
    tPrint = "打印",
    printTitle = "打印布局",
    pQty = "数量",
    pPaper = "纸张大小",
    pCut = "裁切线",
    pDownload = "下载",
    pPrint = "立即打印",
    settingsTitle = "设置",
    sLangSection = "语言",
    sLanguage = "语言",
    sPhotoSection = "照片与质量",
    sQuality = "照片质量",
    sFormat = "保存格式",
    sWatermark = "水印",
    sWatermarkOff = "关闭",
    sAiSection = "AI与自动",
    sFaceAi = "人脸识别",
    sFaceAiSub = "自动调整位置",
    sAutoBg = "自动去背景",
    sAutoBgSub = "拍摄时去除背景",
    sBeauty = "自动美颜",
    sBeautyMode = "自然",
    sPrintSection = "打印",
    sPaperDefault = "默认纸张大小",
    sCutDefault = "默认裁切线",
    sCutOn = "开启",
    sOther = "其他",
    sPrivacy = "隐私",
    sPrivacySub = "离线处理",
    sHelp = "帮助",
    sRate = "给应用评分",
    sVersion = "版本",
    chooseLang = "选择语言",
    sAppearance = "外观",
    sDarkMode = "深色模式",
    sDarkModeAuto = "跟随系统",
    sDarkModeLight = "浅色",
    sDarkModeDark = "深色",
    processing = "正在处理...",
    pipelineFaceMesh = "人脸识别",
    pipelineAlignment = "面部对齐",
    pipelineQuality = "质量检查",
    pipelineSegmentation = "去背景",
    pipelineExport = "导出证件照",
    noFaceDetected = "未检测到人脸",
    noFaceMessage = "照片中未找到人脸。请重新拍摄或选择其他照片。",
    saveSuccess = "照片已保存！",
    saveSuccessMessage = "照片已保存到相册。",
    saveOptionsTitle = "保存选项",
    savePhotoSize = "照片尺寸",
    savePrintCopies = "打印数量",
    saveFormat = "格式",
    saveSingleOnly = "仅保存单张照片",
    saveWithPrintLayout = "保存含打印布局",
    saveSinglePhoto = "单张照片",
    savePrintLayoutLabel = "打印布局",
    savePhotosPerSheet = "%d张/页",
    back = "返回",
    next = "继续",
    cancel = "取消",
    done = "完成",
    error = "错误",
    retry = "重试",
)

val LocalStrings = compositionLocalOf { ViStrings }
val LocalLanguage = compositionLocalOf { AppLanguage.VI }

fun getStrings(language: AppLanguage): Strings = when (language) {
    AppLanguage.VI -> ViStrings
    AppLanguage.EN -> EnStrings
    AppLanguage.JA -> JaStrings
    AppLanguage.ZH -> ZhStrings
}
