package com.idphoto.app.ui

import androidx.compose.runtime.*
import java.util.Locale

/**
 * Hệ thống đa ngôn ngữ — VI, EN, JA, ZH.
 * Tương ứng mockup HTML i18n.
 */

enum class AppLanguage(val code: String, val label: String, val nativeName: String) {
    VI("vi", "VI", "Tiếng Việt"),
    EN("en", "EN", "English"),
    JA("ja", "JA", "日本語"),
    ZH("zh", "ZH", "中文"),
    KR("ko", "KR", "한국어");

    companion object {
        /**
         * Detect app language from the device's system locale.
         * Falls back to English if the system language is not supported.
         */
        fun fromSystemLocale(): AppLanguage {
            val systemLang = Locale.getDefault().language // "vi", "en", "ja", "zh", etc.
            return entries.find { it.code == systemLang } ?: EN
        }
    }
}

data class Strings(
    // Splash
    val splashSub: String,

    // Home
    val homeSub: String,
    val btnCamera: String,
    val btnCameraSub: String,
    val btnGallery: String,
    val btnGallerySub: String,
    val popularSizes: String,
    val popularSizesSub: String,
    val viewAllSizes: String,

    // Size labels
    val szPassport: String,
    val szResume: String,

    // Size select
    val selectSize: String,
    val searchPlaceholder: String,
    val customSize: String,
    val customSizeSub: String,

    // Camera
    val guideTxt: String,
    val tipLight: String,
    val tipFace: String,
    val tipBg: String,
    val selectPhotoHint: String,
    val capturedPhotos: String,
    val deletePhoto: String,

    // Edit
    val editTitle: String,
    val save: String,
    val tCrop: String,
    val tBg: String,
    val tColor: String,
    val tBright: String,
    val tSuit: String,
    val tRotate: String,
    val tPrint: String,
    val pinchToZoomHint: String,
    val panHint: String,
    val zoomLabel: String,
    val zoomIn: String,
    val zoomOut: String,
    val resetZoom: String,

    // Print
    val printTitle: String,
    val pQty: String,
    val pPaper: String,
    val pCut: String,
    val pDownload: String,
    val pPrint: String,

    // Settings
    val settingsTitle: String,
    val sLangSection: String,
    val sLanguage: String,
    val sPhotoSection: String,
    val sQuality: String,
    val sFormat: String,
    val sWatermark: String,
    val sWatermarkOff: String,
    val sAiSection: String,
    val sFaceAi: String,
    val sFaceAiSub: String,
    val sAutoBg: String,
    val sAutoBgSub: String,
    val sBeauty: String,
    val sBeautyMode: String,
    val sPrintSection: String,
    val sPaperDefault: String,
    val sCutDefault: String,
    val sCutOn: String,
    val sOther: String,
    val sPrivacy: String,
    val sPrivacySub: String,
    val sHelp: String,
    val sRate: String,
    val sVersion: String,
    val chooseLang: String,

    // Appearance / Dark mode
    val sAppearance: String,
    val sDarkMode: String,
    val sDarkModeAuto: String,
    val sDarkModeLight: String,
    val sDarkModeDark: String,

    // Processing pipeline
    val processing: String,
    val pipelineFaceMesh: String,
    val pipelineAlignment: String,
    val pipelineQuality: String,
    val pipelineSegmentation: String,
    val pipelineExport: String,

    // Face detection
    val noFaceDetected: String,
    val noFaceMessage: String,

    // Save
    val saveSuccess: String,
    val saveSuccessMessage: String,

    // Save options dialog
    val saveOptionsTitle: String,
    val savePhotoSize: String,
    val savePrintCopies: String,
    val saveFormat: String,
    val saveSingleOnly: String,
    val saveWithPrintLayout: String,
    val saveSinglePhoto: String,
    val savePrintLayoutLabel: String,
    val savePhotosPerSheet: String,

    // Common
    val back: String,
    val next: String,
    val cancel: String,
    val done: String,
    val error: String,
    val retry: String,

    // Edit screen - background tabs
    val bgTabSolid: String,
    val bgTabGradient: String,
    val bgTabStudio: String,

    // Brightness panel
    val brightnessTitle: String,
    val brightnessOriginal: String,

    // Save format descriptions
    val formatHighQuality: String,
    val formatLightweight: String,

    // Pipeline error
    val segmentationError: String,

    // Back confirmation
    val backConfirmMessage: String,
    val backConfirmYes: String,

    // Saving overlay
    val saving: String,

    // Accessibility
    val accessFlash: String,
    val accessFlipCamera: String,

    // Splash screen
    val appName: String,
    val appVersion: String,

    // Processing screen
    val aiProcessingPrivacy: String,
    val stepDone: String,
    val stepRunning: String,
    val stepError: String,
    val stepPending: String,

    // Edit screen
    val contentReset: String,
    val contentClose: String,
    val dpi: String,
    val dpiDraft: String,
    val dpiOk: String,
    val dpiHd: String,
    val dpiPro: String,
    val dpiUltra: String,
    val formatJpeg: String,
    val formatPng: String,
    val formatWebp: String,
    val formatJpegDesc: String,
    val formatPngDesc: String,
    val formatWebpDesc: String,

    // Settings screen
    val faq: String,
    val fiveStars: String,
    val dpiWebScreen: String,
    val dpiStandard: String,
    val dpiHighQuality: String,
    val dpiProfessional: String,
    val dpiUltraHd: String,
    val defaultVersion: String,

    // Photo sizes descriptions
    val size2x3Visa: String,
    val size3x4Cccd: String,
    val size4x6Resume: String,
    val size2x3Student: String,
    val size3x4License: String,
    val size2x2UsPassport: String,
    val size5x5UsVisa: String,
    val size2x2GreenCard: String,
    val size35x45Schengen: String,
    val size35x45EuPassport: String,
    val size35x45UkPassport: String,
    val size3x4JapanPassport: String,
    val size45x45JapanVisa: String,
    val size24x3Zairyu: String,
    val size35x45KoreaPassport: String,
    val size3x4KoreaId: String,
    val size35x45KoreaVisa: String,
    val size33x48ChinaVisa: String,
    val size25x35ChinaId: String,
    val size33x48ChinaPassport: String,
    val size35x45ThailandVisa: String,
    val size25x32ThaiId: String,
    val size35x45AustraliaVisa: String,
    val size35x45AustraliaPassport: String,

    // Country names
    val countryVn: String,
    val countryUs: String,
    val countryEu: String,
    val countryJp: String,
    val countryKr: String,
    val countryCn: String,
    val countryTh: String,
    val countryAu: String,

    // Outfit options
    val outfitNone: String,
    val outfitBlackSuit: String,
    val outfitBlueSuit: String,
    val outfitSuitNoTie: String,
    val outfitWhiteShirt: String,
    val outfitBlueShirt: String,
    val outfitWhiteBlouse: String,
    val outfitAoDai: String,

    // Pipeline step messages
    val pipelineFaceMeshEn: String,
    val pipelineRotation: String,
    val pipelineNoRotation: String,
    val pipelineScore: String,
    val pipelineSkipped: String,

    // Error messages
    val errorCannotReadImage: String,
    val errorUnknown: String,
    val errorSave: String,
    val errorPrefix: String,

    // Print layout
    val photosCount: String,
    val dpiLabel: String,
    val paper4x6: String,
    val paper5x7: String,
    val paperA4: String,
    val paperA5: String,

    // Content descriptions
    val descMinus: String,
    val descPlus: String,

    // Home screen
    val greeting: String,
    val brandName: String,
    val brandTagline: String,
    val titlePart1: String,
    val titlePart2: String,
    val titlePart3: String,
    val aiPoweredTag: String,
    val selectFromGallery: String,
    val aiProcessingTime: String,
    val bgRemovalTitle: String,
    val bgRemovalTech: String,
    val faceAlignmentTitle: String,
    val faceAlignmentTech: String,
    val privacyTitle: String,
    val privacyTech: String,
    val navHome: String,
    val navPhotos: String,
    val navSizes: String,
    val navProfile: String,
    val contentLanguage: String,
    val contentHelp: String,
    val onDeviceLabel: String,
    val viewAll: String,
    val countryVnFlag: String,
    val countryUsFlag: String,
    val countryJpFlag: String,
    val countryEuFlag: String,
    val countryKrFlag: String,
    val hotBadge: String,
    val tipTitle: String,
    val tipDescription: String,

    // Size select — custom size dialog & badges
    val suggestedBadge: String,
    val mostPopularSuffix: String,
    val customNameLabel: String,
    val customNameExample: String,
    val customWidthMmLabel: String,
    val customHeightMmLabel: String,
    val customInvalidSize: String,

    // Language sheet secondary names
    val langSecondaryVi: String,
    val langSecondaryEn: String,
    val langSecondaryJa: String,
    val langSecondaryZh: String,
    val langSecondaryKr: String,

    // Camera live detect
    val cameraAiDetect: String,
    val cameraScanning: String,
    val cameraEditHint: String,

    // Background names (keyed by default Vietnamese)
    val bgNames: Map<String, String>,

    // Outfit names (keyed by default Vietnamese name stored in data class)
    val outfitNamesMap: Map<String, String>,

    // Photo size descriptions (keyed by default Vietnamese/English description in data class)
    val photoSizeDescriptions: Map<String, String>,

    // Country names keyed by code ("VN","US",...)
    val countryNamesByCode: Map<String, String>,
)

/**
 * Default Vietnamese background names used as lookup keys in [Strings.bgNames].
 * Listed here for consistency.
 */
object DefaultBgKeys {
    // Solid
    const val WHITE = "Trắng"
    const val BLUE = "Xanh dương"
    const val RED = "Đỏ"
    const val GREEN = "Xanh lá"
    const val LIGHT_GRAY = "Xám nhạt"
    const val LIGHT_BLUE = "Xanh nhạt"
    const val NAVY = "Xanh navy"
    const val LIGHT_PINK = "Hồng nhạt"
    const val LIGHT_YELLOW = "Vàng nhạt"
    const val DARK_GRAY = "Xám đậm"
    const val TRANSPARENT = "Trong suốt"
    // Gradient
    const val GRAD_SKY = "Xanh trời"
    const val GRAD_SUNSET = "Hoàng hôn"
    const val GRAD_PURPLE_PINK = "Tím hồng"
    const val GRAD_MINT = "Xanh mint"
    const val GRAD_DEEP_BLUE = "Xanh đậm"
    const val GRAD_SILVER = "Xám sang"
    const val GRAD_PASTEL_PINK = "Hồng pastel"
    const val GRAD_WARM_YELLOW = "Vàng ấm"
    // Studio
    const val STUDIO_GRAY = "Studio xám"
    const val STUDIO_BLUE = "Studio xanh"
    const val STUDIO_BLACK = "Studio đen"
    const val STUDIO_WHITE = "Studio trắng"
    const val STUDIO_PURPLE = "Studio tím"
    const val STUDIO_PINK = "Studio hồng"
    const val STUDIO_ORANGE = "Studio cam"
    const val STUDIO_GREEN = "Studio xanh lá"
}

/** Helper lookups. */
fun Strings.localizedBgName(defaultName: String): String = bgNames[defaultName] ?: defaultName
fun Strings.localizedOutfitName(defaultName: String): String = outfitNamesMap[defaultName] ?: defaultName
fun Strings.localizedSizeDescription(defaultDescription: String): String =
    photoSizeDescriptions[defaultDescription] ?: defaultDescription
fun Strings.localizedCountry(code: String): String = countryNamesByCode[code] ?: code

/** Return localized step label for a pipeline step index (0..4). */
fun Strings.pipelineStepLabel(index: Int): String = when (index) {
    0 -> pipelineFaceMesh
    1 -> pipelineAlignment
    2 -> pipelineQuality
    3 -> pipelineSegmentation
    4 -> pipelineExport
    else -> ""
}

val ViStrings = Strings(
    splashSub = "Ảnh thẻ chuyên nghiệp",
    homeSub = "Chụp ảnh thẻ chuyên nghiệp",
    btnCamera = "Chụp ảnh",
    btnCameraSub = "Chụp mới",
    btnGallery = "Thư viện",
    btnGallerySub = "Chọn ảnh có sẵn",
    popularSizes = "Kích cỡ phổ biến",
    popularSizesSub = "Chọn nhanh và chụp ảnh",
    viewAllSizes = "XEM TẤT CẢ KÍCH CỠ",
    szPassport = "Hộ chiếu, Visa",
    szResume = "Sơ yếu lý lịch",
    selectSize = "Chọn kích thước",
    searchPlaceholder = "Tìm kiếm kích thước, quốc gia...",
    customSize = "Tùy chỉnh kích thước",
    customSizeSub = "Nhập kích thước tùy ý",
    guideTxt = "Đặt khuôn mặt vào khung hình",
    tipLight = "Ánh sáng tốt",
    tipFace = "Giữ thẳng mặt",
    tipBg = "Phông nền OK",
    selectPhotoHint = "Chọn ảnh để chỉnh sửa",
    capturedPhotos = "Ảnh đã chụp",
    deletePhoto = "Xóa ảnh",
    editTitle = "Chỉnh sửa",
    save = "Lưu",
    tCrop = "Cắt",
    tBg = "Xóa phông",
    tColor = "Đổi nền",
    tBright = "Độ sáng",
    tSuit = "Đổi áo",
    tRotate = "Xoay",
    tPrint = "In ảnh",
    pinchToZoomHint = "Chụm 2 ngón để zoom · Kéo 1 ngón để di chuyển ảnh",
    panHint = "Kéo để di chuyển",
    zoomLabel = "Zoom",
    zoomIn = "Phóng to",
    zoomOut = "Thu nhỏ",
    resetZoom = "Khôi phục",
    printTitle = "Bố cục in",
    pQty = "Số lượng",
    pPaper = "Khổ giấy",
    pCut = "Đường cắt",
    pDownload = "Tải ảnh",
    pPrint = "In ngay",
    settingsTitle = "Cài đặt",
    sLangSection = "Ngôn ngữ",
    sLanguage = "Ngôn ngữ",
    sPhotoSection = "Ảnh & Chất lượng",
    sQuality = "Chất lượng ảnh",
    sFormat = "Định dạng lưu",
    sWatermark = "Watermark",
    sWatermarkOff = "Tắt",
    sAiSection = "AI & Tự động",
    sFaceAi = "Nhận diện khuôn mặt",
    sFaceAiSub = "Tự động căn chỉnh vị trí",
    sAutoBg = "Tự động xóa phông",
    sAutoBgSub = "Xóa nền khi chụp",
    sBeauty = "Tự động làm đẹp",
    sBeautyMode = "Tự nhiên",
    sPrintSection = "In ảnh",
    sPaperDefault = "Khổ giấy mặc định",
    sCutDefault = "Đường cắt mặc định",
    sCutOn = "Bật",
    sOther = "Khác",
    sPrivacy = "Quyền riêng tư",
    sPrivacySub = "Xử lý ngoại tuyến",
    sHelp = "Trợ giúp",
    sRate = "Đánh giá ứng dụng",
    sVersion = "Phiên bản",
    chooseLang = "Chọn ngôn ngữ",
    sAppearance = "Giao diện",
    sDarkMode = "Chế độ tối",
    sDarkModeAuto = "Hệ thống",
    sDarkModeLight = "Sáng",
    sDarkModeDark = "Tối",
    processing = "Đang xử lý ảnh...",
    pipelineFaceMesh = "Nhận diện khuôn mặt",
    pipelineAlignment = "Căn chỉnh khuôn mặt",
    pipelineQuality = "Kiểm tra chất lượng",
    pipelineSegmentation = "Tách nền ảnh",
    pipelineExport = "Xuất ảnh thẻ",
    noFaceDetected = "Không phát hiện khuôn mặt",
    noFaceMessage = "Không tìm thấy khuôn mặt người trong ảnh. Vui lòng chụp lại hoặc chọn ảnh khác.",
    saveSuccess = "Đã lưu ảnh!",
    saveSuccessMessage = "Ảnh đã được lưu vào thư viện ảnh của bạn.",
    saveOptionsTitle = "Tùy chọn lưu ảnh",
    savePhotoSize = "Cỡ ảnh",
    savePrintCopies = "Số ảnh in",
    saveFormat = "Định dạng",
    saveSingleOnly = "Chỉ lưu ảnh đơn",
    saveWithPrintLayout = "Lưu kèm bố cục in",
    saveSinglePhoto = "Ảnh đơn",
    savePrintLayoutLabel = "Bố cục in",
    savePhotosPerSheet = "%d ảnh/tờ",
    back = "Quay lại",
    next = "Tiếp tục",
    cancel = "Hủy",
    done = "Xong",
    error = "Lỗi",
    retry = "Thử lại",

    bgTabSolid = "Đơn sắc",
    bgTabGradient = "Gradient",
    bgTabStudio = "Studio",
    brightnessTitle = "Độ sáng",
    brightnessOriginal = "Gốc",
    formatHighQuality = "Chất lượng cao",
    formatLightweight = "Nhẹ hơn",
    segmentationError = "Lỗi xóa phông",
    backConfirmMessage = "Bạn có chắc muốn quay lại? Mọi chỉnh sửa chưa lưu sẽ bị mất.",
    backConfirmYes = "Quay lại",
    saving = "Đang lưu ảnh…",
    accessFlash = "Đèn flash",
    accessFlipCamera = "Lật camera",

    // Splash screen
    appName = "ID Photo Pro",
    appVersion = "v2.0 · EXPRESSIVE",

    // Processing screen
    aiProcessingPrivacy = "AI đang xử lý trên thiết bị · 100% riêng tư",
    stepDone = "✓",
    stepRunning = "···",
    stepError = "!",
    stepPending = "—",

    // Edit screen
    contentReset = "Reset",
    contentClose = "Close",
    dpi = "DPI",
    dpiDraft = "Draft",
    dpiOk = "OK",
    dpiHd = "HD ★",
    dpiPro = "Pro",
    dpiUltra = "Ultra",
    formatJpeg = "JPEG",
    formatPng = "PNG",
    formatWebp = "WEBP",
    formatJpegDesc = "Smaller file, good quality",
    formatPngDesc = "Lossless, transparent BG",
    formatWebpDesc = "Modern, small & high quality",

    // Settings screen
    faq = "FAQ",
    fiveStars = "★★★★★",
    dpiWebScreen = "Web / Screen",
    dpiStandard = "Standard",
    dpiHighQuality = "High Quality ★",
    dpiProfessional = "Professional",
    dpiUltraHd = "Ultra HD",
    defaultVersion = "1.0.0",

    // Photo sizes descriptions
    size2x3Visa = "Visa, CMND cũ",
    size3x4Cccd = "CCCD, Hộ chiếu VN",
    size4x6Resume = "Sơ yếu lý lịch, Hồ sơ",
    size2x3Student = "Thẻ sinh viên, Nhân viên",
    size3x4License = "Bằng lái xe (GPLX)",
    size2x2UsPassport = "US Passport",
    size5x5UsVisa = "US Visa",
    size2x2GreenCard = "Green Card",
    size35x45Schengen = "Schengen Visa",
    size35x45EuPassport = "EU Passport",
    size35x45UkPassport = "UK Passport",
    size3x4JapanPassport = "Japan Passport",
    size45x45JapanVisa = "Japan Visa",
    size24x3Zairyu = "Zairyu Card",
    size35x45KoreaPassport = "Korea Passport",
    size3x4KoreaId = "Korea ID Card",
    size35x45KoreaVisa = "Korea Visa",
    size33x48ChinaVisa = "China Visa",
    size25x35ChinaId = "China ID Card",
    size33x48ChinaPassport = "China Passport",
    size35x45ThailandVisa = "Thailand Visa",
    size25x32ThaiId = "Thai ID Card",
    size35x45AustraliaVisa = "Australia Visa",
    size35x45AustraliaPassport = "Australia Passport",

    // Country names
    countryVn = "Việt Nam",
    countryUs = "Mỹ / US",
    countryEu = "Châu Âu",
    countryJp = "Nhật Bản",
    countryKr = "Hàn Quốc",
    countryCn = "Trung Quốc",
    countryTh = "Thái Lan",
    countryAu = "Úc",

    // Outfit options
    outfitNone = "Không",
    outfitBlackSuit = "Vest đen",
    outfitBlueSuit = "Vest xanh",
    outfitSuitNoTie = "Vest (ko cà vạt)",
    outfitWhiteShirt = "Sơ mi trắng",
    outfitBlueShirt = "Sơ mi xanh",
    outfitWhiteBlouse = "Áo nữ trắng",
    outfitAoDai = "Áo dài",

    // Pipeline step messages
    pipelineFaceMeshEn = "FaceMesh Detection",
    pipelineRotation = "Xoay",
    pipelineNoRotation = "Không cần xoay",
    pipelineScore = "Score:",
    pipelineSkipped = "Skipped",

    // Error messages
    errorCannotReadImage = "Cannot read image",
    errorUnknown = "Unknown error",
    errorSave = "Save error:",
    errorPrefix = "Error:",

    // Print layout
    photosCount = "ảnh",
    dpiLabel = "DPI",
    paper4x6 = "4×6 inch",
    paper5x7 = "5×7 inch",
    paperA4 = "A4",
    paperA5 = "A5",

    // Content descriptions
    descMinus = "−",
    descPlus = "+",

    // Home screen
    greeting = "Chào bạn ✨",
    brandName = "IDPhoto",
    brandTagline = "PRO · AI STUDIO",
    titlePart1 = "Ảnh thẻ ",
    titlePart2 = "chuẩn quốc tế",
    titlePart3 = "chỉ trong 30 giây.",
    aiPoweredTag = "✦ AI-POWERED",
    selectFromGallery = "Chọn ảnh từ thư viện của bạn",
    aiProcessingTime = "AI sẽ xử lý ảnh trong khoảng 3 giây.",
    bgRemovalTitle = "Xóa nền AI",
    bgRemovalTech = "Tự động",
    faceAlignmentTitle = "Căn mặt",
    faceAlignmentTech = "Thông minh",
    privacyTitle = "Riêng tư",
    privacyTech = "An toàn",
    navHome = "Trang chủ",
    navPhotos = "Ảnh",
    navSizes = "Kích cỡ",
    navProfile = "Tôi",
    contentLanguage = "Language",
    contentHelp = "Help",
    onDeviceLabel = "100% On-device",
    viewAll = "Xem tất cả",
    countryVnFlag = "🇻🇳 Việt Nam",
    countryUsFlag = "🇺🇸 US",
    countryJpFlag = "🇯🇵 JP",
    countryEuFlag = "🇪🇺 EU",
    countryKrFlag = "🇰🇷 KR",
    hotBadge = "🔥 HOT",
    tipTitle = "Mẹo để có 1 ảnh thẻ đẹp",
    tipDescription = "Chụp trước nền có màu rõ ràng (tường trắng, xanh nhạt), ánh sáng đều — tránh ngược sáng và bóng đổ. Giữ mặt trực diện, vai thẳng, mắt nhìn thẳng vào máy; không đeo kính râm, không che tóc lên trán. Giữ máy ngang tầm mắt, cách mặt khoảng 50–70 cm để AI nhận diện và tách nền chính xác nhất.",

    suggestedBadge = "Gợi ý",
    mostPopularSuffix = "· Phổ biến nhất",
    customNameLabel = "Tên (tuỳ chọn)",
    customNameExample = "VD: 3×4 mm",
    customWidthMmLabel = "Rộng (mm)",
    customHeightMmLabel = "Cao (mm)",
    customInvalidSize = "Vui lòng nhập kích thước hợp lệ",

    langSecondaryVi = "Vietnamese",
    langSecondaryEn = "Tiếng Anh",
    langSecondaryJa = "Tiếng Nhật",
    langSecondaryZh = "Tiếng Trung",
    langSecondaryKr = "Tiếng Hàn",
    cameraAiDetect = "Nhận diện AI",
    cameraScanning = "Đang quét...",
    cameraEditHint = "Chỉnh sửa",

    bgNames = mapOf(
        DefaultBgKeys.WHITE to "Trắng",
        DefaultBgKeys.BLUE to "Xanh dương",
        DefaultBgKeys.RED to "Đỏ",
        DefaultBgKeys.GREEN to "Xanh lá",
        DefaultBgKeys.LIGHT_GRAY to "Xám nhạt",
        DefaultBgKeys.LIGHT_BLUE to "Xanh nhạt",
        DefaultBgKeys.NAVY to "Xanh navy",
        DefaultBgKeys.LIGHT_PINK to "Hồng nhạt",
        DefaultBgKeys.LIGHT_YELLOW to "Vàng nhạt",
        DefaultBgKeys.DARK_GRAY to "Xám đậm",
        DefaultBgKeys.TRANSPARENT to "Trong suốt",
        DefaultBgKeys.GRAD_SKY to "Xanh trời",
        DefaultBgKeys.GRAD_SUNSET to "Hoàng hôn",
        DefaultBgKeys.GRAD_PURPLE_PINK to "Tím hồng",
        DefaultBgKeys.GRAD_MINT to "Xanh mint",
        DefaultBgKeys.GRAD_DEEP_BLUE to "Xanh đậm",
        DefaultBgKeys.GRAD_SILVER to "Xám sang",
        DefaultBgKeys.GRAD_PASTEL_PINK to "Hồng pastel",
        DefaultBgKeys.GRAD_WARM_YELLOW to "Vàng ấm",
        DefaultBgKeys.STUDIO_GRAY to "Studio xám",
        DefaultBgKeys.STUDIO_BLUE to "Studio xanh",
        DefaultBgKeys.STUDIO_BLACK to "Studio đen",
        DefaultBgKeys.STUDIO_WHITE to "Studio trắng",
        DefaultBgKeys.STUDIO_PURPLE to "Studio tím",
        DefaultBgKeys.STUDIO_PINK to "Studio hồng",
        DefaultBgKeys.STUDIO_ORANGE to "Studio cam",
        DefaultBgKeys.STUDIO_GREEN to "Studio xanh lá",
    ),
    outfitNamesMap = mapOf(
        "Không" to "Không",
        "Vest đen" to "Vest đen",
        "Vest xanh" to "Vest xanh",
        "Vest (ko cà vạt)" to "Vest (ko cà vạt)",
        "Sơ mi trắng" to "Sơ mi trắng",
        "Sơ mi xanh" to "Sơ mi xanh",
        "Áo nữ trắng" to "Áo nữ trắng",
        "Áo dài" to "Áo dài",
    ),
    photoSizeDescriptions = mapOf(
        "Visa, CMND cũ" to "Visa, CMND cũ",
        "CCCD, Hộ chiếu VN" to "CCCD, Hộ chiếu VN",
        "Sơ yếu lý lịch, Hồ sơ" to "Sơ yếu lý lịch, Hồ sơ",
        "Thẻ sinh viên, Nhân viên" to "Thẻ sinh viên, Nhân viên",
        "Bằng lái xe (GPLX)" to "Bằng lái xe (GPLX)",
        "US Passport" to "Hộ chiếu Mỹ",
        "US Visa" to "Visa Mỹ",
        "Green Card" to "Thẻ xanh (Green Card)",
        "Schengen Visa" to "Visa Schengen",
        "EU Passport" to "Hộ chiếu EU",
        "UK Passport" to "Hộ chiếu Anh",
        "Japan Passport" to "Hộ chiếu Nhật",
        "Japan Visa" to "Visa Nhật",
        "Zairyu Card" to "Thẻ cư trú Nhật",
        "Korea Passport" to "Hộ chiếu Hàn",
        "Korea ID Card" to "CCCD Hàn Quốc",
        "Korea Visa" to "Visa Hàn",
        "China Visa" to "Visa Trung Quốc",
        "China ID Card" to "CCCD Trung Quốc",
        "China Passport" to "Hộ chiếu Trung Quốc",
        "Thailand Visa" to "Visa Thái Lan",
        "Thai ID Card" to "CCCD Thái Lan",
        "Australia Visa" to "Visa Úc",
        "Australia Passport" to "Hộ chiếu Úc",
    ),
    countryNamesByCode = mapOf(
        "VN" to "Việt Nam",
        "US" to "Mỹ / US",
        "EU" to "Châu Âu",
        "JP" to "Nhật Bản",
        "KR" to "Hàn Quốc",
        "CN" to "Trung Quốc",
        "TH" to "Thái Lan",
        "AU" to "Úc",
    ),
)

val EnStrings = Strings(
    splashSub = "Professional ID Photos",
    homeSub = "Professional ID Photo Maker",
    btnCamera = "Camera",
    btnCameraSub = "Take new photo",
    btnGallery = "Gallery",
    btnGallerySub = "Choose existing",
    popularSizes = "Popular Sizes",
    popularSizesSub = "Quick select and shoot",
    viewAllSizes = "VIEW ALL SIZES",
    szPassport = "Passport, Visa",
    szResume = "Resume / CV",
    selectSize = "Select Size",
    searchPlaceholder = "Search size, country...",
    customSize = "Custom Size",
    customSizeSub = "Enter custom dimensions",
    guideTxt = "Position your face in the frame",
    tipLight = "Good lighting",
    tipFace = "Keep face straight",
    tipBg = "Background OK",
    selectPhotoHint = "Tap a photo to edit",
    capturedPhotos = "Captured photos",
    deletePhoto = "Delete photo",
    editTitle = "Edit Photo",
    save = "Save",
    tCrop = "Crop",
    tBg = "Remove BG",
    tColor = "Background",
    tBright = "Brightness",
    tSuit = "Outfit",
    tRotate = "Rotate",
    tPrint = "Print",
    pinchToZoomHint = "Pinch to zoom · Drag with one finger to move",
    panHint = "Drag to move",
    zoomLabel = "Zoom",
    zoomIn = "Zoom in",
    zoomOut = "Zoom out",
    resetZoom = "Reset",
    printTitle = "Print Layout",
    pQty = "Quantity",
    pPaper = "Paper Size",
    pCut = "Cut Lines",
    pDownload = "Download",
    pPrint = "Print Now",
    settingsTitle = "Settings",
    sLangSection = "Language",
    sLanguage = "Language",
    sPhotoSection = "Photo & Quality",
    sQuality = "Photo Quality",
    sFormat = "Save Format",
    sWatermark = "Watermark",
    sWatermarkOff = "Off",
    sAiSection = "AI & Auto",
    sFaceAi = "Face Detection",
    sFaceAiSub = "Auto-align position",
    sAutoBg = "Auto Remove BG",
    sAutoBgSub = "Remove background on capture",
    sBeauty = "Auto Beauty",
    sBeautyMode = "Natural",
    sPrintSection = "Printing",
    sPaperDefault = "Default Paper Size",
    sCutDefault = "Default Cut Lines",
    sCutOn = "On",
    sOther = "Other",
    sPrivacy = "Privacy",
    sPrivacySub = "Offline processing",
    sHelp = "Help & Support",
    sRate = "Rate this app",
    sVersion = "Version",
    chooseLang = "Choose Language",
    sAppearance = "Appearance",
    sDarkMode = "Dark Mode",
    sDarkModeAuto = "System",
    sDarkModeLight = "Light",
    sDarkModeDark = "Dark",
    processing = "Processing photo...",
    pipelineFaceMesh = "Face Detection",
    pipelineAlignment = "Face Alignment",
    pipelineQuality = "Quality Check",
    pipelineSegmentation = "Background Removal",
    pipelineExport = "Export ID Photo",
    noFaceDetected = "No face detected",
    noFaceMessage = "No human face was found in the photo. Please retake or choose another image.",
    saveSuccess = "Photo saved!",
    saveSuccessMessage = "Photo has been saved to your gallery.",
    saveOptionsTitle = "Save Options",
    savePhotoSize = "Photo Size",
    savePrintCopies = "Print Copies",
    saveFormat = "Format",
    saveSingleOnly = "Save single photo only",
    saveWithPrintLayout = "Save with print layout",
    saveSinglePhoto = "Single Photo",
    savePrintLayoutLabel = "Print Layout",
    savePhotosPerSheet = "%d photos/sheet",
    back = "Back",
    next = "Next",
    cancel = "Cancel",
    done = "Done",
    error = "Error",
    retry = "Retry",

    bgTabSolid = "Solid",
    bgTabGradient = "Gradient",
    bgTabStudio = "Studio",
    brightnessTitle = "Brightness",
    brightnessOriginal = "Original",
    formatHighQuality = "High quality",
    formatLightweight = "Lightweight",
    segmentationError = "Segmentation error",
    backConfirmMessage = "Are you sure you want to go back? All unsaved changes will be lost.",
    backConfirmYes = "Go back",
    saving = "Saving photo…",
    accessFlash = "Flash",
    accessFlipCamera = "Flip camera",

    // Splash screen
    appName = "ID Photo Pro",
    appVersion = "v2.0 · EXPRESSIVE",

    // Processing screen
    aiProcessingPrivacy = "AI processing on device · 100% private",
    stepDone = "✓",
    stepRunning = "···",
    stepError = "!",
    stepPending = "—",

    // Edit screen
    contentReset = "Reset",
    contentClose = "Close",
    dpi = "DPI",
    dpiDraft = "Draft",
    dpiOk = "OK",
    dpiHd = "HD ★",
    dpiPro = "Pro",
    dpiUltra = "Ultra",
    formatJpeg = "JPEG",
    formatPng = "PNG",
    formatWebp = "WEBP",
    formatJpegDesc = "Smaller file, good quality",
    formatPngDesc = "Lossless, transparent BG",
    formatWebpDesc = "Modern, small & high quality",

    // Settings screen
    faq = "FAQ",
    fiveStars = "★★★★★",
    dpiWebScreen = "Web / Screen",
    dpiStandard = "Standard",
    dpiHighQuality = "High Quality ★",
    dpiProfessional = "Professional",
    dpiUltraHd = "Ultra HD",
    defaultVersion = "1.0.0",

    // Photo sizes descriptions
    size2x3Visa = "Visa, Old ID",
    size3x4Cccd = "CCCD, VN Passport",
    size4x6Resume = "Resume, Documents",
    size2x3Student = "Student, Employee",
    size3x4License = "Driver License",
    size2x2UsPassport = "US Passport",
    size5x5UsVisa = "US Visa",
    size2x2GreenCard = "Green Card",
    size35x45Schengen = "Schengen Visa",
    size35x45EuPassport = "EU Passport",
    size35x45UkPassport = "UK Passport",
    size3x4JapanPassport = "Japan Passport",
    size45x45JapanVisa = "Japan Visa",
    size24x3Zairyu = "Zairyu Card",
    size35x45KoreaPassport = "Korea Passport",
    size3x4KoreaId = "Korea ID Card",
    size35x45KoreaVisa = "Korea Visa",
    size33x48ChinaVisa = "China Visa",
    size25x35ChinaId = "China ID Card",
    size33x48ChinaPassport = "China Passport",
    size35x45ThailandVisa = "Thailand Visa",
    size25x32ThaiId = "Thai ID Card",
    size35x45AustraliaVisa = "Australia Visa",
    size35x45AustraliaPassport = "Australia Passport",

    // Country names
    countryVn = "Vietnam",
    countryUs = "USA",
    countryEu = "Europe",
    countryJp = "Japan",
    countryKr = "Korea",
    countryCn = "China",
    countryTh = "Thailand",
    countryAu = "Australia",

    // Outfit options
    outfitNone = "None",
    outfitBlackSuit = "Black Suit",
    outfitBlueSuit = "Blue Suit",
    outfitSuitNoTie = "Suit (No Tie)",
    outfitWhiteShirt = "White Shirt",
    outfitBlueShirt = "Blue Shirt",
    outfitWhiteBlouse = "White Blouse",
    outfitAoDai = "Ao Dai",

    // Pipeline step messages
    pipelineFaceMeshEn = "FaceMesh Detection",
    pipelineRotation = "Rotate",
    pipelineNoRotation = "No rotation needed",
    pipelineScore = "Score:",
    pipelineSkipped = "Skipped",

    // Error messages
    errorCannotReadImage = "Cannot read image",
    errorUnknown = "Unknown error",
    errorSave = "Save error:",
    errorPrefix = "Error:",

    // Print layout
    photosCount = "photos",
    dpiLabel = "DPI",
    paper4x6 = "4×6 inch",
    paper5x7 = "5×7 inch",
    paperA4 = "A4",
    paperA5 = "A5",

    // Content descriptions
    descMinus = "−",
    descPlus = "+",

    // Home screen
    greeting = "Hello ✨",
    brandName = "IDPhoto",
    brandTagline = "PRO · AI STUDIO",
    titlePart1 = "International ",
    titlePart2 = "ID Photo",
    titlePart3 = "in just 30 seconds.",
    aiPoweredTag = "✦ AI-POWERED",
    selectFromGallery = "Select photo from your gallery",
    aiProcessingTime = "AI will process your photo in about 3 seconds.",
    bgRemovalTitle = "AI Background Removal",
    bgRemovalTech = "Automatic",
    faceAlignmentTitle = "Face Alignment",
    faceAlignmentTech = "Smart",
    privacyTitle = "Privacy",
    privacyTech = "Secure",
    navHome = "Home",
    navPhotos = "Photos",
    navSizes = "Sizes",
    navProfile = "Profile",
    contentLanguage = "Language",
    contentHelp = "Help",
    onDeviceLabel = "100% On-device",
    viewAll = "View All",
    countryVnFlag = "🇻🇳 Vietnam",
    countryUsFlag = "🇺🇸 US",
    countryJpFlag = "🇯🇵 JP",
    countryEuFlag = "🇪🇺 EU",
    countryKrFlag = "🇰🇷 KR",
    hotBadge = "🔥 HOT",
    tipTitle = "Tips for a great ID photo",
    tipDescription = "Shoot against a plain, clearly colored background (white or light blue wall) with even lighting — avoid backlight and harsh shadows. Keep your face forward, shoulders straight, eyes on the camera; no sunglasses and no hair covering your forehead. Hold the camera at eye level about 50–70 cm (20–28 in) away so the AI can detect and segment you precisely.",

    suggestedBadge = "Recommended",
    mostPopularSuffix = "· Most popular",
    customNameLabel = "Name (optional)",
    customNameExample = "e.g. 3×4 mm",
    customWidthMmLabel = "Width (mm)",
    customHeightMmLabel = "Height (mm)",
    customInvalidSize = "Please enter a valid size",

    langSecondaryVi = "Vietnamese",
    langSecondaryEn = "English",
    langSecondaryJa = "Japanese",
    langSecondaryZh = "Chinese",
    langSecondaryKr = "Korean",
    cameraAiDetect = "AI Detect",
    cameraScanning = "Scanning...",
    cameraEditHint = "Edit",

    bgNames = mapOf(
        DefaultBgKeys.WHITE to "White",
        DefaultBgKeys.BLUE to "Blue",
        DefaultBgKeys.RED to "Red",
        DefaultBgKeys.GREEN to "Green",
        DefaultBgKeys.LIGHT_GRAY to "Light gray",
        DefaultBgKeys.LIGHT_BLUE to "Light blue",
        DefaultBgKeys.NAVY to "Navy",
        DefaultBgKeys.LIGHT_PINK to "Light pink",
        DefaultBgKeys.LIGHT_YELLOW to "Light yellow",
        DefaultBgKeys.DARK_GRAY to "Dark gray",
        DefaultBgKeys.TRANSPARENT to "Transparent",
        DefaultBgKeys.GRAD_SKY to "Sky",
        DefaultBgKeys.GRAD_SUNSET to "Sunset",
        DefaultBgKeys.GRAD_PURPLE_PINK to "Purple-Pink",
        DefaultBgKeys.GRAD_MINT to "Mint",
        DefaultBgKeys.GRAD_DEEP_BLUE to "Deep blue",
        DefaultBgKeys.GRAD_SILVER to "Silver",
        DefaultBgKeys.GRAD_PASTEL_PINK to "Pastel pink",
        DefaultBgKeys.GRAD_WARM_YELLOW to "Warm yellow",
        DefaultBgKeys.STUDIO_GRAY to "Studio gray",
        DefaultBgKeys.STUDIO_BLUE to "Studio blue",
        DefaultBgKeys.STUDIO_BLACK to "Studio black",
        DefaultBgKeys.STUDIO_WHITE to "Studio white",
        DefaultBgKeys.STUDIO_PURPLE to "Studio purple",
        DefaultBgKeys.STUDIO_PINK to "Studio pink",
        DefaultBgKeys.STUDIO_ORANGE to "Studio orange",
        DefaultBgKeys.STUDIO_GREEN to "Studio green",
    ),
    outfitNamesMap = mapOf(
        "Không" to "None",
        "Vest đen" to "Black Suit",
        "Vest xanh" to "Blue Suit",
        "Vest (ko cà vạt)" to "Suit (No Tie)",
        "Sơ mi trắng" to "White Shirt",
        "Sơ mi xanh" to "Blue Shirt",
        "Áo nữ trắng" to "White Blouse",
        "Áo dài" to "Ao Dai",
    ),
    photoSizeDescriptions = mapOf(
        "Visa, CMND cũ" to "Visa, Old ID",
        "CCCD, Hộ chiếu VN" to "CCCD, VN Passport",
        "Sơ yếu lý lịch, Hồ sơ" to "Resume, Documents",
        "Thẻ sinh viên, Nhân viên" to "Student, Employee",
        "Bằng lái xe (GPLX)" to "Driver License",
        "US Passport" to "US Passport",
        "US Visa" to "US Visa",
        "Green Card" to "Green Card",
        "Schengen Visa" to "Schengen Visa",
        "EU Passport" to "EU Passport",
        "UK Passport" to "UK Passport",
        "Japan Passport" to "Japan Passport",
        "Japan Visa" to "Japan Visa",
        "Zairyu Card" to "Zairyu Card",
        "Korea Passport" to "Korea Passport",
        "Korea ID Card" to "Korea ID Card",
        "Korea Visa" to "Korea Visa",
        "China Visa" to "China Visa",
        "China ID Card" to "China ID Card",
        "China Passport" to "China Passport",
        "Thailand Visa" to "Thailand Visa",
        "Thai ID Card" to "Thai ID Card",
        "Australia Visa" to "Australia Visa",
        "Australia Passport" to "Australia Passport",
    ),
    countryNamesByCode = mapOf(
        "VN" to "Vietnam",
        "US" to "USA",
        "EU" to "Europe",
        "JP" to "Japan",
        "KR" to "Korea",
        "CN" to "China",
        "TH" to "Thailand",
        "AU" to "Australia",
    ),
)

val JaStrings = Strings(
    splashSub = "プロの証明写真",
    homeSub = "プロの証明写真アプリ",
    btnCamera = "撮影",
    btnCameraSub = "新しく撮る",
    btnGallery = "ギャラリー",
    btnGallerySub = "既存の写真を選択",
    popularSizes = "よく使うサイズ",
    popularSizesSub = "すぐに選んで撮影",
    viewAllSizes = "すべてのサイズを見る",
    szPassport = "パスポート・ビザ",
    szResume = "履歴書",
    selectSize = "サイズを選択",
    searchPlaceholder = "サイズ、国名を検索...",
    customSize = "カスタムサイズ",
    customSizeSub = "任意のサイズを入力",
    guideTxt = "顔を枠内に合わせてください",
    tipLight = "照明OK",
    tipFace = "正面を向く",
    tipBg = "背景OK",
    selectPhotoHint = "写真をタップして編集",
    capturedPhotos = "撮影した写真",
    deletePhoto = "写真を削除",
    editTitle = "写真を編集",
    save = "保存",
    tCrop = "切取",
    tBg = "背景除去",
    tColor = "背景色",
    tBright = "明るさ",
    tSuit = "衣装",
    tRotate = "回転",
    tPrint = "印刷",
    pinchToZoomHint = "ピンチでズーム・1本指で画像を移動",
    panHint = "ドラッグで移動",
    zoomLabel = "ズーム",
    zoomIn = "拡大",
    zoomOut = "縮小",
    resetZoom = "リセット",
    printTitle = "印刷レイアウト",
    pQty = "枚数",
    pPaper = "用紙サイズ",
    pCut = "切取線",
    pDownload = "ダウンロード",
    pPrint = "印刷する",
    settingsTitle = "設定",
    sLangSection = "言語",
    sLanguage = "言語",
    sPhotoSection = "写真と品質",
    sQuality = "写真品質",
    sFormat = "保存形式",
    sWatermark = "ウォーターマーク",
    sWatermarkOff = "オフ",
    sAiSection = "AI & 自動",
    sFaceAi = "顔認識",
    sFaceAiSub = "自動位置調整",
    sAutoBg = "自動背景除去",
    sAutoBgSub = "撮影時に背景を除去",
    sBeauty = "自動美肌",
    sBeautyMode = "ナチュラル",
    sPrintSection = "印刷",
    sPaperDefault = "デフォルト用紙サイズ",
    sCutDefault = "デフォルト切取線",
    sCutOn = "オン",
    sOther = "その他",
    sPrivacy = "プライバシー",
    sPrivacySub = "オフライン処理",
    sHelp = "ヘルプ",
    sRate = "アプリを評価",
    sVersion = "バージョン",
    chooseLang = "言語を選択",
    sAppearance = "外観",
    sDarkMode = "ダークモード",
    sDarkModeAuto = "システム",
    sDarkModeLight = "ライト",
    sDarkModeDark = "ダーク",
    processing = "処理中...",
    pipelineFaceMesh = "顔認識",
    pipelineAlignment = "顔の位置調整",
    pipelineQuality = "品質チェック",
    pipelineSegmentation = "背景除去",
    pipelineExport = "証明写真を出力",
    noFaceDetected = "顔が検出されません",
    noFaceMessage = "写真に人の顔が見つかりませんでした。撮り直すか、別の写真を選択してください。",
    saveSuccess = "写真を保存しました！",
    saveSuccessMessage = "写真がギャラリーに保存されました。",
    saveOptionsTitle = "保存オプション",
    savePhotoSize = "写真サイズ",
    savePrintCopies = "印刷枚数",
    saveFormat = "フォーマット",
    saveSingleOnly = "単体写真のみ保存",
    saveWithPrintLayout = "印刷レイアウト付きで保存",
    saveSinglePhoto = "単体写真",
    savePrintLayoutLabel = "印刷レイアウト",
    savePhotosPerSheet = "%d枚/シート",
    back = "戻る",
    next = "次へ",
    cancel = "キャンセル",
    done = "完了",
    error = "エラー",
    retry = "再試行",

    bgTabSolid = "単色",
    bgTabGradient = "グラデ",
    bgTabStudio = "スタジオ",
    brightnessTitle = "明るさ",
    brightnessOriginal = "元の値",
    formatHighQuality = "高品質",
    formatLightweight = "軽量",
    segmentationError = "背景除去エラー",
    backConfirmMessage = "戻りますか？保存されていない変更はすべて失われます。",
    backConfirmYes = "戻る",
    saving = "写真を保存中…",
    accessFlash = "フラッシュ",
    accessFlipCamera = "カメラ切替",

    // Splash screen
    appName = "ID Photo Pro",
    appVersion = "v2.0 · EXPRESSIVE",

    // Processing screen
    aiProcessingPrivacy = "AIが端末で処理中 · 100%プライベート",
    stepDone = "✓",
    stepRunning = "···",
    stepError = "!",
    stepPending = "—",

    // Edit screen
    contentReset = "リセット",
    contentClose = "閉じる",
    dpi = "DPI",
    dpiDraft = "下書き",
    dpiOk = "OK",
    dpiHd = "HD ★",
    dpiPro = "プロ",
    dpiUltra = "ウルトラ",
    formatJpeg = "JPEG",
    formatPng = "PNG",
    formatWebp = "WEBP",
    formatJpegDesc = "小さなファイル、良好な品質",
    formatPngDesc = "可逆圧縮、透明背景",
    formatWebpDesc = "モダン、小さく高品質",

    // Settings screen
    faq = "FAQ",
    fiveStars = "★★★★★",
    dpiWebScreen = "Web / 画面",
    dpiStandard = "標準",
    dpiHighQuality = "高品質 ★",
    dpiProfessional = "プロフェッショナル",
    dpiUltraHd = "ウルトラHD",
    defaultVersion = "1.0.0",

    // Photo sizes descriptions
    size2x3Visa = "ビザ、旧身分証",
    size3x4Cccd = "CCCD、ベトナムパスポート",
    size4x6Resume = "履歴書、書類",
    size2x3Student = "学生証、社員証",
    size3x4License = "運転免許証",
    size2x2UsPassport = "米国パスポート",
    size5x5UsVisa = "米国ビザ",
    size2x2GreenCard = "グリーンカード",
    size35x45Schengen = "シェンゲンビザ",
    size35x45EuPassport = "EUパスポート",
    size35x45UkPassport = "英国パスポート",
    size3x4JapanPassport = "日本パスポート",
    size45x45JapanVisa = "日本ビザ",
    size24x3Zairyu = "在留カード",
    size35x45KoreaPassport = "韓国パスポート",
    size3x4KoreaId = "韓国IDカード",
    size35x45KoreaVisa = "韓国ビザ",
    size33x48ChinaVisa = "中国ビザ",
    size25x35ChinaId = "中国IDカード",
    size33x48ChinaPassport = "中国パスポート",
    size35x45ThailandVisa = "タイビザ",
    size25x32ThaiId = "タイIDカード",
    size35x45AustraliaVisa = "オーストラリアビザ",
    size35x45AustraliaPassport = "オーストラリアパスポート",

    // Country names
    countryVn = "ベトナム",
    countryUs = "アメリカ",
    countryEu = "ヨーロッパ",
    countryJp = "日本",
    countryKr = "韓国",
    countryCn = "中国",
    countryTh = "タイ",
    countryAu = "オーストラリア",

    // Outfit options
    outfitNone = "なし",
    outfitBlackSuit = "黒スーツ",
    outfitBlueSuit = "青スーツ",
    outfitSuitNoTie = "スーツ（ネクなし）",
    outfitWhiteShirt = "白シャツ",
    outfitBlueShirt = "青シャツ",
    outfitWhiteBlouse = "白ブラウス",
    outfitAoDai = "アオザイ",

    // Pipeline step messages
    pipelineFaceMeshEn = "顔メッシュ検出",
    pipelineRotation = "回転",
    pipelineNoRotation = "回転不要",
    pipelineScore = "スコア:",
    pipelineSkipped = "スキップ",

    // Error messages
    errorCannotReadImage = "画像を読み込めません",
    errorUnknown = "不明なエラー",
    errorSave = "保存エラー:",
    errorPrefix = "エラー:",

    // Print layout
    photosCount = "枚",
    dpiLabel = "DPI",
    paper4x6 = "4×6インチ",
    paper5x7 = "5×7インチ",
    paperA4 = "A4",
    paperA5 = "A5",

    // Content descriptions
    descMinus = "−",
    descPlus = "+",

    // Home screen
    greeting = "こんにちは ✨",
    brandName = "IDPhoto",
    brandTagline = "PRO · AI STUDIO",
    titlePart1 = "国際的な",
    titlePart2 = "証明写真",
    titlePart3 = "わずか30秒で。",
    aiPoweredTag = "✦ AI-POWERED",
    selectFromGallery = "ギャラリーから写真を選択",
    aiProcessingTime = "AIは約3秒で写真を処理します。",
    bgRemovalTitle = "AI背景削除",
    bgRemovalTech = "自動",
    faceAlignmentTitle = "顔の整列",
    faceAlignmentTech = "スマート",
    privacyTitle = "プライバシー",
    privacyTech = "安全",
    navHome = "ホーム",
    navPhotos = "写真",
    navSizes = "サイズ",
    navProfile = "プロフィール",
    contentLanguage = "言語",
    contentHelp = "ヘルプ",
    onDeviceLabel = "100% オンデバイス",
    viewAll = "すべて見る",
    countryVnFlag = "🇻🇳 ベトナム",
    countryUsFlag = "🇺🇸 アメリカ",
    countryJpFlag = "🇯🇵 日本",
    countryEuFlag = "🇪🇺 欧州",
    countryKrFlag = "🇰🇷 韓国",
    hotBadge = "🔥 HOT",
    tipTitle = "きれいな証明写真を撮るコツ",
    tipDescription = "白い壁や淡いブルーなど、色がはっきりした無地の背景で撮影し、照明は均一に — 逆光や強い影は避けましょう。正面を向き、肩をまっすぐに、目線はカメラへ。サングラスはNG、前髪で額を隠さないでください。カメラは目の高さに構え、顔から50〜70cm離すとAIがきれいに切り抜きできます。",

    suggestedBadge = "おすすめ",
    mostPopularSuffix = "· 最も人気",
    customNameLabel = "名前（任意）",
    customNameExample = "例: 3×4 mm",
    customWidthMmLabel = "幅 (mm)",
    customHeightMmLabel = "高さ (mm)",
    customInvalidSize = "有効なサイズを入力してください",

    langSecondaryVi = "ベトナム語",
    langSecondaryEn = "英語",
    langSecondaryJa = "日本語",
    langSecondaryZh = "中国語",
    langSecondaryKr = "韓国語",
    cameraAiDetect = "AI検出",
    cameraScanning = "スキャン中...",
    cameraEditHint = "編集",

    bgNames = mapOf(
        DefaultBgKeys.WHITE to "白",
        DefaultBgKeys.BLUE to "青",
        DefaultBgKeys.RED to "赤",
        DefaultBgKeys.GREEN to "緑",
        DefaultBgKeys.LIGHT_GRAY to "ライトグレー",
        DefaultBgKeys.LIGHT_BLUE to "ライトブルー",
        DefaultBgKeys.NAVY to "ネイビー",
        DefaultBgKeys.LIGHT_PINK to "ライトピンク",
        DefaultBgKeys.LIGHT_YELLOW to "ライトイエロー",
        DefaultBgKeys.DARK_GRAY to "ダークグレー",
        DefaultBgKeys.TRANSPARENT to "透明",
        DefaultBgKeys.GRAD_SKY to "スカイ",
        DefaultBgKeys.GRAD_SUNSET to "サンセット",
        DefaultBgKeys.GRAD_PURPLE_PINK to "紫ピンク",
        DefaultBgKeys.GRAD_MINT to "ミント",
        DefaultBgKeys.GRAD_DEEP_BLUE to "ディープブルー",
        DefaultBgKeys.GRAD_SILVER to "シルバー",
        DefaultBgKeys.GRAD_PASTEL_PINK to "パステルピンク",
        DefaultBgKeys.GRAD_WARM_YELLOW to "ウォームイエロー",
        DefaultBgKeys.STUDIO_GRAY to "スタジオグレー",
        DefaultBgKeys.STUDIO_BLUE to "スタジオブルー",
        DefaultBgKeys.STUDIO_BLACK to "スタジオブラック",
        DefaultBgKeys.STUDIO_WHITE to "スタジオホワイト",
        DefaultBgKeys.STUDIO_PURPLE to "スタジオパープル",
        DefaultBgKeys.STUDIO_PINK to "スタジオピンク",
        DefaultBgKeys.STUDIO_ORANGE to "スタジオオレンジ",
        DefaultBgKeys.STUDIO_GREEN to "スタジオグリーン",
    ),
    outfitNamesMap = mapOf(
        "Không" to "なし",
        "Vest đen" to "黒スーツ",
        "Vest xanh" to "青スーツ",
        "Vest (ko cà vạt)" to "スーツ（ネクなし）",
        "Sơ mi trắng" to "白シャツ",
        "Sơ mi xanh" to "青シャツ",
        "Áo nữ trắng" to "白ブラウス",
        "Áo dài" to "アオザイ",
    ),
    photoSizeDescriptions = mapOf(
        "Visa, CMND cũ" to "ビザ、旧身分証",
        "CCCD, Hộ chiếu VN" to "CCCD、ベトナムパスポート",
        "Sơ yếu lý lịch, Hồ sơ" to "履歴書、書類",
        "Thẻ sinh viên, Nhân viên" to "学生証、社員証",
        "Bằng lái xe (GPLX)" to "運転免許証",
        "US Passport" to "米国パスポート",
        "US Visa" to "米国ビザ",
        "Green Card" to "グリーンカード",
        "Schengen Visa" to "シェンゲンビザ",
        "EU Passport" to "EUパスポート",
        "UK Passport" to "英国パスポート",
        "Japan Passport" to "日本パスポート",
        "Japan Visa" to "日本ビザ",
        "Zairyu Card" to "在留カード",
        "Korea Passport" to "韓国パスポート",
        "Korea ID Card" to "韓国IDカード",
        "Korea Visa" to "韓国ビザ",
        "China Visa" to "中国ビザ",
        "China ID Card" to "中国IDカード",
        "China Passport" to "中国パスポート",
        "Thailand Visa" to "タイビザ",
        "Thai ID Card" to "タイIDカード",
        "Australia Visa" to "オーストラリアビザ",
        "Australia Passport" to "オーストラリアパスポート",
    ),
    countryNamesByCode = mapOf(
        "VN" to "ベトナム",
        "US" to "アメリカ",
        "EU" to "ヨーロッパ",
        "JP" to "日本",
        "KR" to "韓国",
        "CN" to "中国",
        "TH" to "タイ",
        "AU" to "オーストラリア",
    ),
)

val ZhStrings = Strings(
    splashSub = "专业证件照",
    homeSub = "专业证件照制作",
    btnCamera = "拍照",
    btnCameraSub = "拍摄新照片",
    btnGallery = "相册",
    btnGallerySub = "选择已有照片",
    popularSizes = "常用尺寸",
    popularSizesSub = "快速选择并拍摄",
    viewAllSizes = "查看所有尺寸",
    szPassport = "护照、签证",
    szResume = "简历",
    selectSize = "选择尺寸",
    searchPlaceholder = "搜索尺寸、国家...",
    customSize = "自定义尺寸",
    customSizeSub = "输入自定义尺寸",
    guideTxt = "将面部对准框内",
    tipLight = "光线良好",
    tipFace = "保持正面",
    tipBg = "背景OK",
    selectPhotoHint = "点击照片进行编辑",
    capturedPhotos = "已拍照片",
    deletePhoto = "删除照片",
    editTitle = "编辑照片",
    save = "保存",
    tCrop = "裁剪",
    tBg = "去背景",
    tColor = "换背景",
    tBright = "亮度",
    tSuit = "换装",
    tRotate = "旋转",
    tPrint = "打印",
    pinchToZoomHint = "捏合缩放 · 单指拖动移动图片",
    panHint = "拖动移动",
    zoomLabel = "缩放",
    zoomIn = "放大",
    zoomOut = "缩小",
    resetZoom = "重置",
    printTitle = "打印布局",
    pQty = "数量",
    pPaper = "纸张大小",
    pCut = "裁切线",
    pDownload = "下载",
    pPrint = "立即打印",
    settingsTitle = "设置",
    sLangSection = "语言",
    sLanguage = "语言",
    sPhotoSection = "照片与质量",
    sQuality = "照片质量",
    sFormat = "保存格式",
    sWatermark = "水印",
    sWatermarkOff = "关闭",
    sAiSection = "AI与自动",
    sFaceAi = "人脸识别",
    sFaceAiSub = "自动调整位置",
    sAutoBg = "自动去背景",
    sAutoBgSub = "拍摄时去除背景",
    sBeauty = "自动美颜",
    sBeautyMode = "自然",
    sPrintSection = "打印",
    sPaperDefault = "默认纸张大小",
    sCutDefault = "默认裁切线",
    sCutOn = "开启",
    sOther = "其他",
    sPrivacy = "隐私",
    sPrivacySub = "离线处理",
    sHelp = "帮助",
    sRate = "给应用评分",
    sVersion = "版本",
    chooseLang = "选择语言",
    sAppearance = "外观",
    sDarkMode = "深色模式",
    sDarkModeAuto = "跟随系统",
    sDarkModeLight = "浅色",
    sDarkModeDark = "深色",
    processing = "正在处理...",
    pipelineFaceMesh = "人脸识别",
    pipelineAlignment = "面部对齐",
    pipelineQuality = "质量检查",
    pipelineSegmentation = "去背景",
    pipelineExport = "导出证件照",
    noFaceDetected = "未检测到人脸",
    noFaceMessage = "照片中未找到人脸。请重新拍摄或选择其他照片。",
    saveSuccess = "照片已保存！",
    saveSuccessMessage = "照片已保存到相册。",
    saveOptionsTitle = "保存选项",
    savePhotoSize = "照片尺寸",
    savePrintCopies = "打印数量",
    saveFormat = "格式",
    saveSingleOnly = "仅保存单张照片",
    saveWithPrintLayout = "保存含打印布局",
    saveSinglePhoto = "单张照片",
    savePrintLayoutLabel = "打印布局",
    savePhotosPerSheet = "%d张/页",
    back = "返回",
    next = "继续",
    cancel = "取消",
    done = "完成",
    error = "错误",
    retry = "重试",

    bgTabSolid = "纯色",
    bgTabGradient = "渐变",
    bgTabStudio = "影楼",
    brightnessTitle = "亮度",
    brightnessOriginal = "原始",
    formatHighQuality = "高质量",
    formatLightweight = "更轻量",
    segmentationError = "去背景错误",
    backConfirmMessage = "确定要返回吗？所有未保存的更改将会丢失。",
    backConfirmYes = "返回",
    saving = "正在保存照片…",
    accessFlash = "闪光灯",
    accessFlipCamera = "翻转相机",

    // Splash screen
    appName = "ID Photo Pro",
    appVersion = "v2.0 · EXPRESSIVE",

    // Processing screen
    aiProcessingPrivacy = "AI正在设备上处理 · 100%隐私",
    stepDone = "✓",
    stepRunning = "···",
    stepError = "!",
    stepPending = "—",

    // Edit screen
    contentReset = "重置",
    contentClose = "关闭",
    dpi = "DPI",
    dpiDraft = "草稿",
    dpiOk = "OK",
    dpiHd = "高清 ★",
    dpiPro = "专业",
    dpiUltra = "超清",
    formatJpeg = "JPEG",
    formatPng = "PNG",
    formatWebp = "WEBP",
    formatJpegDesc = "文件较小，质量良好",
    formatPngDesc = "无损，透明背景",
    formatWebpDesc = "现代，小而高质量",

    // Settings screen
    faq = "FAQ",
    fiveStars = "★★★★★",
    dpiWebScreen = "Web / 屏幕",
    dpiStandard = "标准",
    dpiHighQuality = "高质量 ★",
    dpiProfessional = "专业",
    dpiUltraHd = "超高清",
    defaultVersion = "1.0.0",

    // Photo sizes descriptions
    size2x3Visa = "签证，旧身份证",
    size3x4Cccd = "CCCD，越南护照",
    size4x6Resume = "简历，文件",
    size2x3Student = "学生证，员工证",
    size3x4License = "驾驶证",
    size2x2UsPassport = "美国护照",
    size5x5UsVisa = "美国签证",
    size2x2GreenCard = "绿卡",
    size35x45Schengen = "申根签证",
    size35x45EuPassport = "欧盟护照",
    size35x45UkPassport = "英国护照",
    size3x4JapanPassport = "日本护照",
    size45x45JapanVisa = "日本签证",
    size24x3Zairyu = "在留卡",
    size35x45KoreaPassport = "韩国护照",
    size3x4KoreaId = "韩国身份证",
    size35x45KoreaVisa = "韩国签证",
    size33x48ChinaVisa = "中国签证",
    size25x35ChinaId = "中国身份证",
    size33x48ChinaPassport = "中国护照",
    size35x45ThailandVisa = "泰国签证",
    size25x32ThaiId = "泰国身份证",
    size35x45AustraliaVisa = "澳大利亚签证",
    size35x45AustraliaPassport = "澳大利亚护照",

    // Country names
    countryVn = "越南",
    countryUs = "美国",
    countryEu = "欧洲",
    countryJp = "日本",
    countryKr = "韩国",
    countryCn = "中国",
    countryTh = "泰国",
    countryAu = "澳大利亚",

    // Outfit options
    outfitNone = "无",
    outfitBlackSuit = "黑色西装",
    outfitBlueSuit = "蓝色西装",
    outfitSuitNoTie = "西装（无领带）",
    outfitWhiteShirt = "白衬衫",
    outfitBlueShirt = "蓝衬衫",
    outfitWhiteBlouse = "白色女衬衫",
    outfitAoDai = "奥黛",

    // Pipeline step messages
    pipelineFaceMeshEn = "面部网格检测",
    pipelineRotation = "旋转",
    pipelineNoRotation = "无需旋转",
    pipelineScore = "得分:",
    pipelineSkipped = "跳过",

    // Error messages
    errorCannotReadImage = "无法读取图像",
    errorUnknown = "未知错误",
    errorSave = "保存错误:",
    errorPrefix = "错误:",

    // Print layout
    photosCount = "张",
    dpiLabel = "DPI",
    paper4x6 = "4×6英寸",
    paper5x7 = "5×7英寸",
    paperA4 = "A4",
    paperA5 = "A5",

    // Content descriptions
    descMinus = "−",
    descPlus = "+",

    // Home screen
    greeting = "你好 ✨",
    brandName = "IDPhoto",
    brandTagline = "PRO · AI STUDIO",
    titlePart1 = "国际",
    titlePart2 = "证件照",
    titlePart3 = "仅需30秒。",
    aiPoweredTag = "✦ AI-POWERED",
    selectFromGallery = "从图库选择照片",
    aiProcessingTime = "AI将在约3秒内处理您的照片。",
    bgRemovalTitle = "AI背景移除",
    bgRemovalTech = "自动",
    faceAlignmentTitle = "人脸对齐",
    faceAlignmentTech = "智能",
    privacyTitle = "隐私",
    privacyTech = "安全",
    navHome = "首页",
    navPhotos = "照片",
    navSizes = "尺寸",
    navProfile = "我的",
    contentLanguage = "语言",
    contentHelp = "帮助",
    onDeviceLabel = "100% 本地处理",
    viewAll = "查看全部",
    countryVnFlag = "🇻🇳 越南",
    countryUsFlag = "🇺🇸 美国",
    countryJpFlag = "🇯🇵 日本",
    countryEuFlag = "🇪🇺 欧洲",
    countryKrFlag = "🇰🇷 韩国",
    hotBadge = "🔥 HOT",
    tipTitle = "拍出精美证件照的小技巧",
    tipDescription = "请在颜色清晰的纯色背景前拍摄（白色或浅蓝色墙面），光线均匀 — 避免逆光和明显阴影。正面朝向，肩膀放平，眼睛直视镜头；不要戴墨镜，不要让头发遮住额头。将手机举至与眼睛齐平，距离面部约 50–70 cm，AI 能更精准地识别并抠图。",

    suggestedBadge = "推荐",
    mostPopularSuffix = "· 最受欢迎",
    customNameLabel = "名称（可选）",
    customNameExample = "例如：3×4 mm",
    customWidthMmLabel = "宽 (mm)",
    customHeightMmLabel = "高 (mm)",
    customInvalidSize = "请输入有效尺寸",

    langSecondaryVi = "越南语",
    langSecondaryEn = "英语",
    langSecondaryJa = "日语",
    langSecondaryZh = "中文",
    langSecondaryKr = "韩语",
    cameraAiDetect = "AI 检测",
    cameraScanning = "扫描中...",
    cameraEditHint = "编辑",

    bgNames = mapOf(
        DefaultBgKeys.WHITE to "白色",
        DefaultBgKeys.BLUE to "蓝色",
        DefaultBgKeys.RED to "红色",
        DefaultBgKeys.GREEN to "绿色",
        DefaultBgKeys.LIGHT_GRAY to "浅灰",
        DefaultBgKeys.LIGHT_BLUE to "浅蓝",
        DefaultBgKeys.NAVY to "藏青",
        DefaultBgKeys.LIGHT_PINK to "浅粉",
        DefaultBgKeys.LIGHT_YELLOW to "浅黄",
        DefaultBgKeys.DARK_GRAY to "深灰",
        DefaultBgKeys.TRANSPARENT to "透明",
        DefaultBgKeys.GRAD_SKY to "天空蓝",
        DefaultBgKeys.GRAD_SUNSET to "日落",
        DefaultBgKeys.GRAD_PURPLE_PINK to "紫粉",
        DefaultBgKeys.GRAD_MINT to "薄荷",
        DefaultBgKeys.GRAD_DEEP_BLUE to "深蓝",
        DefaultBgKeys.GRAD_SILVER to "银色",
        DefaultBgKeys.GRAD_PASTEL_PINK to "粉彩粉",
        DefaultBgKeys.GRAD_WARM_YELLOW to "暖黄",
        DefaultBgKeys.STUDIO_GRAY to "影楼灰",
        DefaultBgKeys.STUDIO_BLUE to "影楼蓝",
        DefaultBgKeys.STUDIO_BLACK to "影楼黑",
        DefaultBgKeys.STUDIO_WHITE to "影楼白",
        DefaultBgKeys.STUDIO_PURPLE to "影楼紫",
        DefaultBgKeys.STUDIO_PINK to "影楼粉",
        DefaultBgKeys.STUDIO_ORANGE to "影楼橙",
        DefaultBgKeys.STUDIO_GREEN to "影楼绿",
    ),
    outfitNamesMap = mapOf(
        "Không" to "无",
        "Vest đen" to "黑色西装",
        "Vest xanh" to "蓝色西装",
        "Vest (ko cà vạt)" to "西装（无领带）",
        "Sơ mi trắng" to "白衬衫",
        "Sơ mi xanh" to "蓝衬衫",
        "Áo nữ trắng" to "白色女衬衫",
        "Áo dài" to "奥黛",
    ),
    photoSizeDescriptions = mapOf(
        "Visa, CMND cũ" to "签证，旧身份证",
        "CCCD, Hộ chiếu VN" to "CCCD，越南护照",
        "Sơ yếu lý lịch, Hồ sơ" to "简历，文件",
        "Thẻ sinh viên, Nhân viên" to "学生证，员工证",
        "Bằng lái xe (GPLX)" to "驾驶证",
        "US Passport" to "美国护照",
        "US Visa" to "美国签证",
        "Green Card" to "绿卡",
        "Schengen Visa" to "申根签证",
        "EU Passport" to "欧盟护照",
        "UK Passport" to "英国护照",
        "Japan Passport" to "日本护照",
        "Japan Visa" to "日本签证",
        "Zairyu Card" to "在留卡",
        "Korea Passport" to "韩国护照",
        "Korea ID Card" to "韩国身份证",
        "Korea Visa" to "韩国签证",
        "China Visa" to "中国签证",
        "China ID Card" to "中国身份证",
        "China Passport" to "中国护照",
        "Thailand Visa" to "泰国签证",
        "Thai ID Card" to "泰国身份证",
        "Australia Visa" to "澳大利亚签证",
        "Australia Passport" to "澳大利亚护照",
    ),
    countryNamesByCode = mapOf(
        "VN" to "越南",
        "US" to "美国",
        "EU" to "欧洲",
        "JP" to "日本",
        "KR" to "韩国",
        "CN" to "中国",
        "TH" to "泰国",
        "AU" to "澳大利亚",
    ),
)

val KrStrings = Strings(
    // Splash
    splashSub = "전문 증명사진",
    // Home
    homeSub = "전문 증명사진 제작",
    btnCamera = "촬영",
    btnCameraSub = "새로 촬영",
    btnGallery = "갤러리",
    btnGallerySub = "기존 사진 선택",
    popularSizes = "인기 크기",
    popularSizesSub = "가장 많이 사용되는 크기",
    viewAllSizes = "모든 크기 보기",
    szPassport = "여권용",
    szResume = "이력서용",
    selectSize = "크기 선택",
    searchPlaceholder = "검색...",
    customSize = "사용자 지정",
    customSizeSub = "사용자 정의 크기 입력",

    // Camera
    guideTxt = "얼굴이 타원 안에 들어가도록 하세요",
    tipLight = "조명이 균일해야 합니다",
    tipFace = "정면을 응시하세요",
    tipBg = "단색 배경이 좋습니다",
    selectPhotoHint = "사진 선택",
    capturedPhotos = "촬영된 사진",
    deletePhoto = "삭제",

    // Edit
    editTitle = "편집",
    save = "저장",
    tCrop = "자르기",
    tBg = "배경",
    tColor = "색상",
    tBright = "밝기",
    tSuit = "정장",
    tRotate = "회전",
    tPrint = "인쇄",
    pinchToZoomHint = "핀치로 확대/축소 · 한 손가락으로 드래그해 이동",
    panHint = "드래그로 이동",
    zoomLabel = "확대/축소",
    zoomIn = "확대",
    zoomOut = "축소",
    resetZoom = "재설정",

    // Print
    printTitle = "인쇄",
    pQty = "수량",
    pPaper = "용지",
    pCut = "자르기",
    pDownload = "다운로드",
    pPrint = "인쇄",

    // Settings
    settingsTitle = "설정",
    sLangSection = "언어",
    sLanguage = "언어",
    sPhotoSection = "사진",
    sQuality = "품질",
    sFormat = "형식",
    sWatermark = "워터마크",
    sWatermarkOff = "끔",
    sAiSection = "AI",
    sFaceAi = "얼굴 AI",
    sFaceAiSub = "얼굴 감지 및 정렬",
    sAutoBg = "자동 배경",
    sAutoBgSub = "배경 자동 제거",
    sBeauty = "뷰티",
    sBeautyMode = "뷰티 모드",
    sPrintSection = "인쇄",
    sPaperDefault = "기본 용지",
    sCutDefault = "기본 자르기",
    sCutOn = "켜기",
    sOther = "기타",
    sPrivacy = "개인정보",
    sPrivacySub = "개인정보 처리방침",
    sHelp = "도움말",
    sRate = "평가",
    sVersion = "버전",
    chooseLang = "언어 선택",

    // Appearance
    sAppearance = "모양",
    sDarkMode = "다크 모드",
    sDarkModeAuto = "자동",
    sDarkModeLight = "밝게",
    sDarkModeDark = "어둡게",

    // Processing
    processing = "처리 중...",
    pipelineFaceMesh = "얼굴 메쉬 감지",
    pipelineAlignment = "얼굴 정렬",
    pipelineQuality = "품질 확인",
    pipelineSegmentation = "배경 제거",
    pipelineExport = "내보내기",

    // Face detection
    noFaceDetected = "얼굴을 감지하지 못했습니다",
    noFaceMessage = "얼굴이 명확하게 보이는 사진을 선택해주세요",

    // Save
    saveSuccess = "저장 완료",
    saveSuccessMessage = "사진이 갤러리에 저장되었습니다",

    // Save options
    saveOptionsTitle = "저장 옵션",
    savePhotoSize = "사진 크기",
    savePrintCopies = "인쇄 매수",
    saveFormat = "형식",
    saveSingleOnly = "단일 사진만",
    saveWithPrintLayout = "인쇄 레이아웃 포함",
    saveSinglePhoto = "단일 사진",
    savePrintLayoutLabel = "인쇄 레이아웃",
    savePhotosPerSheet = "매수당 사진",

    // Common
    back = "뒤로",
    next = "다음",
    cancel = "취소",
    done = "완료",
    error = "오류",
    retry = "다시 시도",

    // Edit screen - background tabs
    bgTabSolid = "단색",
    bgTabGradient = "그라데이션",
    bgTabStudio = "스튜디오",

    // Brightness
    brightnessTitle = "밝기",
    brightnessOriginal = "원본",

    // Format descriptions
    formatHighQuality = "고품질",
    formatLightweight = "가벼움",

    // Pipeline error
    segmentationError = "배경 제거 오류",

    // Back confirmation
    backConfirmMessage = "뒤로 가시겠습니까? 저장되지 않은 변경 사항이 모두 손실됩니다.",
    backConfirmYes = "뒤로 가기",

    // Saving
    saving = "사진 저장 중…",

    // Accessibility
    accessFlash = "플래시",
    accessFlipCamera = "카메라 전환",

    // Splash
    appName = "ID Photo Pro",
    appVersion = "v2.0 · EXPRESSIVE",

    // Processing screen
    aiProcessingPrivacy = "AI가 기기에서 처리 중 · 100% 프라이빗",
    stepDone = "✓",
    stepRunning = "···",
    stepError = "!",
    stepPending = "—",

    // Edit screen
    contentReset = "재설정",
    contentClose = "닫기",
    dpi = "DPI",
    dpiDraft = "초안",
    dpiOk = "OK",
    dpiHd = "HD ★",
    dpiPro = "프로",
    dpiUltra = "울트라",
    formatJpeg = "JPEG",
    formatPng = "PNG",
    formatWebp = "WEBP",
    formatJpegDesc = "작은 파일, 좋은 품질",
    formatPngDesc = "무손실, 투명 배경",
    formatWebpDesc = "현대적, 작고 고품질",

    // Settings
    faq = "FAQ",
    fiveStars = "★★★★★",
    dpiWebScreen = "웹 / 화면",
    dpiStandard = "표준",
    dpiHighQuality = "고품질 ★",
    dpiProfessional = "프로페셔널",
    dpiUltraHd = "울트라 HD",
    defaultVersion = "1.0.0",

    // Photo sizes
    size2x3Visa = "비자, 구형 신분증",
    size3x4Cccd = "CCCD, 베트남 여권",
    size4x6Resume = "이력서, 서류",
    size2x3Student = "학생증, 직원증",
    size3x4License = "운전면허증",
    size2x2UsPassport = "미국 여권",
    size5x5UsVisa = "미국 비자",
    size2x2GreenCard = "그린카드",
    size35x45Schengen = "솅겐 비자",
    size35x45EuPassport = "EU 여권",
    size35x45UkPassport = "영국 여권",
    size3x4JapanPassport = "일본 여권",
    size45x45JapanVisa = "일본 비자",
    size24x3Zairyu = "재류카드",
    size35x45KoreaPassport = "한국 여권",
    size3x4KoreaId = "한국 신분증",
    size35x45KoreaVisa = "한국 비자",
    size33x48ChinaVisa = "중국 비자",
    size25x35ChinaId = "중국 신분증",
    size33x48ChinaPassport = "중국 여권",
    size35x45ThailandVisa = "태국 비자",
    size25x32ThaiId = "태국 신분증",
    size35x45AustraliaVisa = "호주 비자",
    size35x45AustraliaPassport = "호주 여권",

    // Countries
    countryVn = "베트남",
    countryUs = "미국",
    countryEu = "유럽",
    countryJp = "일본",
    countryKr = "한국",
    countryCn = "중국",
    countryTh = "태국",
    countryAu = "호주",

    // Outfits
    outfitNone = "없음",
    outfitBlackSuit = "검은색 정장",
    outfitBlueSuit = "파란색 정장",
    outfitSuitNoTie = "정장 (넥타이 없음)",
    outfitWhiteShirt = "흰색 셔츠",
    outfitBlueShirt = "파란색 셔츠",
    outfitWhiteBlouse = "흰색 블라우스",
    outfitAoDai = "아오자이",

    // Pipeline
    pipelineFaceMeshEn = "얼굴 메쉬 감지",
    pipelineRotation = "회전",
    pipelineNoRotation = "회전 필요 없음",
    pipelineScore = "점수:",
    pipelineSkipped = "건너뜀",

    // Errors
    errorCannotReadImage = "이미지를 읽을 수 없습니다",
    errorUnknown = "알 수 없는 오류",
    errorSave = "저장 오류:",
    errorPrefix = "오류:",

    // Print
    photosCount = "장",
    dpiLabel = "DPI",
    paper4x6 = "4×6인치",
    paper5x7 = "5×7인치",
    paperA4 = "A4",
    paperA5 = "A5",

    // Content descriptions
    descMinus = "−",
    descPlus = "+",

    // Home screen
    greeting = "안녕하세요 ✨",
    brandName = "IDPhoto",
    brandTagline = "PRO · AI STUDIO",
    titlePart1 = "국제 ",
    titlePart2 = "증명사진",
    titlePart3 = "단 30초 만에.",
    aiPoweredTag = "✦ AI-POWERED",
    selectFromGallery = "갤러리에서 사진 선택",
    aiProcessingTime = "AI는 약 3초 내에 사진을 처리합니다.",
    bgRemovalTitle = "AI 배경 제거",
    bgRemovalTech = "자동",
    faceAlignmentTitle = "얼굴 정렬",
    faceAlignmentTech = "스마트",
    privacyTitle = "프라이버시",
    privacyTech = "안전",
    navHome = "홈",
    navPhotos = "사진",
    navSizes = "크기",
    navProfile = "프로필",
    contentLanguage = "언어",
    contentHelp = "도움말",
    onDeviceLabel = "100% 기기 내",
    viewAll = "모두 보기",
    countryVnFlag = "🇻🇳 베트남",
    countryUsFlag = "🇺🇸 미국",
    countryJpFlag = "🇯🇵 일본",
    countryEuFlag = "🇪🇺 유럽",
    countryKrFlag = "🇰🇷 한국",
    hotBadge = "🔥 HOT",
    tipTitle = "멋진 증명사진을 위한 팁",
    tipDescription = "색이 뚜렷한 단색 배경(흰 벽 또는 연한 파랑) 앞에서 촬영하고, 조명은 균일하게 — 역광과 짙은 그림자는 피하세요. 얼굴은 정면, 어깨는 수평, 시선은 카메라를 향하게. 선글라스 착용 금지, 앞머리로 이마를 가리지 마세요. 카메라는 눈높이로, 얼굴에서 50–70 cm 정도 떨어져 들면 AI가 더 정확하게 인식하고 배경을 분리합니다.",

    suggestedBadge = "추천",
    mostPopularSuffix = "· 가장 인기",
    customNameLabel = "이름 (선택)",
    customNameExample = "예: 3×4 mm",
    customWidthMmLabel = "가로 (mm)",
    customHeightMmLabel = "세로 (mm)",
    customInvalidSize = "올바른 크기를 입력하세요",

    langSecondaryVi = "베트남어",
    langSecondaryEn = "영어",
    langSecondaryJa = "일본어",
    langSecondaryZh = "중국어",
    langSecondaryKr = "한국어",
    cameraAiDetect = "AI 감지",
    cameraScanning = "스캔 중...",
    cameraEditHint = "편집",

    bgNames = mapOf(
        DefaultBgKeys.WHITE to "흰색",
        DefaultBgKeys.BLUE to "파란색",
        DefaultBgKeys.RED to "빨간색",
        DefaultBgKeys.GREEN to "초록색",
        DefaultBgKeys.LIGHT_GRAY to "연한 회색",
        DefaultBgKeys.LIGHT_BLUE to "연한 파랑",
        DefaultBgKeys.NAVY to "네이비",
        DefaultBgKeys.LIGHT_PINK to "연한 분홍",
        DefaultBgKeys.LIGHT_YELLOW to "연한 노랑",
        DefaultBgKeys.DARK_GRAY to "진한 회색",
        DefaultBgKeys.TRANSPARENT to "투명",
        DefaultBgKeys.GRAD_SKY to "하늘색",
        DefaultBgKeys.GRAD_SUNSET to "노을",
        DefaultBgKeys.GRAD_PURPLE_PINK to "보라핑크",
        DefaultBgKeys.GRAD_MINT to "민트",
        DefaultBgKeys.GRAD_DEEP_BLUE to "딥블루",
        DefaultBgKeys.GRAD_SILVER to "실버",
        DefaultBgKeys.GRAD_PASTEL_PINK to "파스텔 핑크",
        DefaultBgKeys.GRAD_WARM_YELLOW to "따뜻한 노랑",
        DefaultBgKeys.STUDIO_GRAY to "스튜디오 회색",
        DefaultBgKeys.STUDIO_BLUE to "스튜디오 파랑",
        DefaultBgKeys.STUDIO_BLACK to "스튜디오 검정",
        DefaultBgKeys.STUDIO_WHITE to "스튜디오 흰색",
        DefaultBgKeys.STUDIO_PURPLE to "스튜디오 보라",
        DefaultBgKeys.STUDIO_PINK to "스튜디오 분홍",
        DefaultBgKeys.STUDIO_ORANGE to "스튜디오 주황",
        DefaultBgKeys.STUDIO_GREEN to "스튜디오 초록",
    ),
    outfitNamesMap = mapOf(
        "Không" to "없음",
        "Vest đen" to "검은색 정장",
        "Vest xanh" to "파란색 정장",
        "Vest (ko cà vạt)" to "정장 (넥타이 없음)",
        "Sơ mi trắng" to "흰색 셔츠",
        "Sơ mi xanh" to "파란색 셔츠",
        "Áo nữ trắng" to "흰색 블라우스",
        "Áo dài" to "아오자이",
    ),
    photoSizeDescriptions = mapOf(
        "Visa, CMND cũ" to "비자, 구형 신분증",
        "CCCD, Hộ chiếu VN" to "CCCD, 베트남 여권",
        "Sơ yếu lý lịch, Hồ sơ" to "이력서, 서류",
        "Thẻ sinh viên, Nhân viên" to "학생증, 직원증",
        "Bằng lái xe (GPLX)" to "운전면허증",
        "US Passport" to "미국 여권",
        "US Visa" to "미국 비자",
        "Green Card" to "그린카드",
        "Schengen Visa" to "솅겐 비자",
        "EU Passport" to "EU 여권",
        "UK Passport" to "영국 여권",
        "Japan Passport" to "일본 여권",
        "Japan Visa" to "일본 비자",
        "Zairyu Card" to "재류카드",
        "Korea Passport" to "한국 여권",
        "Korea ID Card" to "한국 신분증",
        "Korea Visa" to "한국 비자",
        "China Visa" to "중국 비자",
        "China ID Card" to "중국 신분증",
        "China Passport" to "중국 여권",
        "Thailand Visa" to "태국 비자",
        "Thai ID Card" to "태국 신분증",
        "Australia Visa" to "호주 비자",
        "Australia Passport" to "호주 여권",
    ),
    countryNamesByCode = mapOf(
        "VN" to "베트남",
        "US" to "미국",
        "EU" to "유럽",
        "JP" to "일본",
        "KR" to "한국",
        "CN" to "중국",
        "TH" to "태국",
        "AU" to "호주",
    ),
)

val LocalStrings = compositionLocalOf { getStrings(AppLanguage.fromSystemLocale()) }
val LocalLanguage = compositionLocalOf { AppLanguage.fromSystemLocale() }

fun getStrings(language: AppLanguage): Strings = when (language) {
    AppLanguage.VI -> ViStrings
    AppLanguage.EN -> EnStrings
    AppLanguage.JA -> JaStrings
    AppLanguage.ZH -> ZhStrings
    AppLanguage.KR -> KrStrings
}
